### ISSUE TITLE
Nginx Example returning 503 response

### ISSUE THREAD

**Issue by liamawhite** [ehazlett/interlock#101]
When running the NGINX example (and presumably the NGINX swarm example) I get a 503 response.

This seems to be caused by commented out server block below in the NGINX config file. When I comment out this block the example works as expected but whenever I scale the app interlock overwrites the file resulting in the 503 returning.

````
# default host return 503
#    server {
#            listen 80;
#            server_name _;
#
#            location / {
#                return 503;
#            }
#
#            location /nginx_status {
#                stub_status on;
#                access_log off;
#            }
#    }


    upstream test.local {
        zone test.local_backend 64k;

        server 172.17.0.1:32770;
        server 172.17.0.1:32768;

    }
    server {
        listen 80;

        server_name test.local;

        location / {
            proxy_pass http://test.local;
        }
    }
````

**Comment by everett-toews** [comment]
Read [How nginx processes a request](http://nginx.org/en/docs/http/request_processing.html)

>In this configuration nginx tests only the request’s header field “Host” to determine which server the request should be routed to. If its value does not match any server name, or the request does not contain this header field at all, then nginx will route the request to the default server for this port.

In this case your `server_name` is `test.local` meaning a client must be making a request to that domain to get routed to your containers.

Try `curl -H 'Host: test.local' http://xxx.xxx.xxx.xxx/`

**Comment by ehazlett** [comment]
Yes as @everett-toews said, use host headers and it will update as containers come and go.

**Comment by liamawhite** [comment]
@everett-toews Thanks! I figured it was something to do with my lack of nginx knowledge. I had started reading through the docs but hadn't got to that part yet.
