### ISSUE TITLE
interlock cannot connect to engine

### ISSUE THREAD

**Issue by runseb** [ehazlett/interlock#102]
Hi,

I have been trying this example https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx-swarm today.
I use it on a swarm started with docker-machine. My swarm uses a consul based discovery. It works fine without interlock.

If I try the example, interlock does not seem to run:

```
$ docker-compose -f docker-interlock.yml logs interlock
Attaching to test_interlock_1
interlock_1 | time="2016-03-21T18:30:55Z" level=info msg="interlock 1.0.0 (49863fc)" 
interlock_1 | time="2016-03-21T18:30:55Z" level=error msg="Cannot connect to the docker engine endpoint" 
interlock_1 | time="2016-03-21T18:30:55Z" level=error msg="event stream fail; attempting to reconnect" 
interlock_1 | time="2016-03-21T18:30:55Z" level=info msg="waiting for event stream to become ready" ```


Which prevents nginx configuration from existing etc etc...

Is the dockerURL correct in the config.toml ? Does this work in all Swarms...?

-sebastien

**Comment by everett-toews** [comment]
What's the `DockerURL` in your `config.toml`?

It should be `docker-machine ip swarm-master`. e.g.

    DockerURL = "tcp://192.168.99.100:2376"

**Comment by ehazlett** [comment]
You will need to replace that example with your Swarm URL.  You will also
need to check if you are using TLS. There are several options; I would
recommend starting with the regular non-TLS TCP socket in Swarm (the
default) to get familiar.

**Comment by runseb** [comment]
everything is setup with docker-machine so there is TLS .

**Comment by everett-toews** [comment]
I amended my above comment to be a more complete example with TLS.

**Comment by runseb** [comment]
@everett-toews thanks, but those volume mounts for the CERTS are not going to work on a Swarm cluster.

All my certs are on my local machine. Those certs actually exist on the master node but I don't think there is a need to mount, and they will be the correct ones only if we bind the interlock container to the master node via constraints.

Or I am totally confused.

**Comment by runseb** [comment]
Never mind, got confused (getting late)..the volume mount is local...

**Comment by runseb** [comment]
ok, got a bit further. Thank @everett-toews the config worked.

However the nginx conf does not get updated with IP addresses of the containers:

```
$ docker-compose -f docker-interlock.yml logs interlock
Attaching to test_interlock_1
interlock_1 | time="2016-03-21T20:01:43Z" level=info msg="interlock 1.1.0-dev (9d1bcfb)" 
interlock_1 | time="2016-03-21T20:01:43Z" level=info msg="interlock node: id=24176a6477dae4036ce6f93f4e4b7f35c7763d064adc4e6c27bcd5ff07b7a21a" ext=lb 
interlock_1 | time="2016-03-21T20:01:56Z" level=info msg="ghost.local: upstream=:" ext=nginx 
interlock_1 | time="2016-03-21T20:02:16Z" level=info msg="ghost.local: upstream=:" ext=nginx 
interlock_1 | time="2016-03-21T20:09:42Z" level=info msg="ghost.local: upstream=:" ext=nginx 
```

This leads to an nginx conf like this:

```
    server {
        listen 80;

        server_name ghost.local;
        
        location / {
            proxy_pass http://ghost.local;
        }
    }
```

**Comment by everett-toews** [comment]
Ah. I suspect you're using an overlay network. If so, you've run into #88. Work is ongoing in the [overlay-support](https://github.com/ehazlett/interlock/tree/overlay-support) branch. You can test it out with the `ehazlett/interlock:overlay` image.

And you can work around it for now by just publishing the ports and interlock will pick them up as normal.

**Comment by ehazlett** [comment]
This should be working in the `1.1.0` release.  Closing.  Please open a new issue if you continue to have trouble.  Thanks!
