### ISSUE TITLE
Compiling on OS X

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#106]
Hi again.  I cloned the repo locally and changed a few files.  I can run `make build` just fine as well as `make image` but when I try running a container I get

`ERROR: 500 Internal Server Error: Cannot start container 07e264978e89f23abce32540037d7a5a9040482113707d20bfe13026d0425502: [9] System error: exec format error`

I'm running on OS X so I looked at the Makefile and changed the `GOOS` to `darwin` and the `GOARCH` to `arm`, `386`, and `arm64`, none of which worked.  I'm pretty new to go so after none of those worked I didn't really know what to do.  I was wondering if you could point me in the right direction.

**Comment by ehazlett** [comment]
This is because Interlock runs in a container and you are building an OS X
binary.  Try setting GOOS=linux and GOARCH=amd64.  That should result in a
working image.  I had a "build-container" target in the past to build in a
container.  I will add that back.  For now, you can use the env var as a
workaround.

**Comment by krishamoud** [comment]
Sorry.  When I tried to `make build` it the first time I had GOOS=linux and GOARCH=amd64 and then ran `make image` I got the same error.

**Comment by ehazlett** [comment]
There was an issue with the Makefile.  Please pull and try again.

**Comment by krishamoud** [comment]
I'm still getting the same error

**Comment by ehazlett** [comment]
Ok pull again.  I just added a `build-container` target and set the default to build in a container.  This should result in a working image (I just tested on OS X).

**Comment by krishamoud** [comment]
It works!  Thanks again for you help!  I appreciate it.
