### ISSUE TITLE
Multiple SSL frontends for HAProxy

### ISSUE THREAD

**Issue by tpbowden** [ehazlett/interlock#107]
Is there a technical reason why (as far as I can tell) it's only possible to use one SSL frontend in HAProxy whereas Nginx can configure a path to cert and key per hostname?

**Comment by ehazlett** [comment]
No technical reason.  We should just need to add to the interlock data and use SNI in haproxy.

**Comment by tpbowden** [comment]
OK thanks, I'll look into it if I have enough time over the weekend

**Comment by tpbowden** [comment]
Realised this has already been implemented. HAProxy can take a directory instead of PEM file for `ssl crt`, and then uses the hostname to pick the correct file. So for `http://test.local` HAProxy would try to find a file called `<cert directory>/test.local.pem`.
