### ISSUE TITLE
Suggestion: Add possibility to specify external Nginx config template

### ISSUE THREAD

**Issue by iiezhachenko** [ehazlett/interlock#116]
Hi,
Interlock is great!
I need Nginx config different from template used by Interlock. Would be great, if I can specify path to external template file.

Currently I'm going to try modifying existing template and rebuilding Interlock.

**Comment by mbentley** [comment]
See #91(issue) and #113 (PR)

**Comment by iiezhachenko** [comment]
Thanks. Missed #91 somehow.
