### ISSUE TITLE
Interlock and nginx containers must be co located with swarm manager/host with tls certs

### ISSUE THREAD

**Issue by Richard-Mathie** [ehazlett/interlock#117]
Is it a requirement that the interlock and nginx containers must reside on the same host which contains either a swarm manager container, or a host which has the access to the tls certs for the host which dose have the swarm manager container.

That is how are you guys doing this in the examples, as I cannot get this to work unless I do co locate these containers, or locate them from the management node which has the tls certs (used docker-machine to launch other nodes), and all the tutorials completely gloss over this issue, which makes me wonder if I am doing it wrong.

Are you syncing the tls certs to the other hosts some how, vire rsync or ssh? so that we can mount the folder with the certs e.g.
```
-v /var/lib/boot2docker:/var/lib/boot2docker
```
Or do you always have to have a swarm management container around so you can mount the local docker socket
```
-v /var/run/docker.sock:/var/run/docker.sock
```

Also without using a volume driver like flocker or rexray how are you supposed to have the nginx and interlock containers on different hosts/ have multiple nginix proxies?

**Comment by ehazlett** [comment]
> Is it a requirement that the interlock and nginx containers must reside on the same host which contains either a swarm manager container, or a host which has the access to the tls certs for the host which dose have the swarm manager container.

No.  You simply need to have access to Swarm.  This can be from a socket or TCP connection (most likely).  If you use TLS with Swarm, Interlock will need access to the certs as well.  You will need to specify the corresponding certs for the `TLSCACert`, `TLSCert` and `TLSKey` settings.  If you are not familiar with using TLS for Docker, see https://docs.docker.com/engine/security/https/.

Starting in the latest version `1.1.0` you do not even need to use a Docker Volume.  Interlock will locate all of the proxy containers (nginx/haproxy) and update accordingly.

> Are you syncing the tls certs to the other hosts some how, vire rsync or ssh?

No we do not do anything with the certs.  If you are using TLS you will need to make sure Interlock has access to the appropriate certificates to access Swarm.  Since Interlock runs in a container you will need to mostly use a volume mount to expose the certificates to the Interlock container.  

> Or do you always have to have a swarm management container around so you can mount the local docker socket

You need access to the Docker API.  This can be from a socket or TCP.  It's up to you.  The examples show both ways.  

> Also without using a volume driver like flocker or rexray how are you supposed to have the nginx and interlock containers on different hosts/ have multiple nginix proxies?

Starting in 1.1.0, we use the `attach` and `archive` endpoints to inject the configuration to all of the proxy containers.  Thus it is not required to run the Interlock containers on the same hosts.  It is also no longer required to use volumes.

**Comment by Richard-Mathie** [comment]
Hey thanks for the speedy reply

> No we do not do anything with the certs. If you are using TLS you will need to make sure Interlock has access to the appropriate certificates to access Swarm. Since Interlock runs in a container you will need to mostly use a volume mount to expose the certificates to the Interlock container.

So normally how do you get those certificates onto the host which is running the interlock container?

I am instantiating my host nodes form a "management" node on aws using docker-machine. The certificates for each nodes docker engine therefore reside on this "management" node. Should I just generate some new certificates for the container to authenticate with the swarm master node, and copy those to a mountable location for the interlock container volume?

**Comment by mbentley** [comment]
If you're setting up a swarm cluster using docker-machine, you can actually use the certs in `/etc/docker` to talk to your cluster as they're signed for client usage as well.  For example with an older version of Interlock:

```
docker run -d -p 80:80 -p 443:443 --restart=always \
    --name interlock \
    -v /etc/docker:/etc/docker:ro \
    -v /data/ssl:/ssl \
    -e NGINX_SSL_CERT_DIR=/ssl \
    ehazlett/interlock:0.3.3 \
    --swarm-url=tcp://$(docker-machine ip ${NAME_PREFIX}-master):3376 \
    --swarm-tls-ca-cert=/etc/docker/ca.pem \
    --swarm-tls-cert=/etc/docker/server.pem \
    --swarm-tls-key=/etc/docker/server-key.pem \
    --plugin nginx \
    start
```

You might want to verify the names of the certs in `/etc/docker` as for all I know, they've changed recently.

**Comment by Richard-Mathie** [comment]
Right yeah, just figured out `/etc/docker` works by doing `docker inspect swarm-manager`. I then got it running thanks to the latest [example ](https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx/docker-compose.yml).

Interestingly you need to use 
```
configPath = "/etc/nginx/nginx.conf"
pidPath = "/tmp/nginx.pid"
```
For configuration else nginx falls over on start up before interlock can attach.

Thanks for the help.

As an aside is there any plans to add locations labels so we can proxy off the routes, instead of having to create an external dns entry for every service?

Ric

**Comment by ehazlett** [comment]
@Richard-Mathie You can use DNS wildcards.  I'm not what you mean by location labels as the browser sends a host header in order to route.  Unless you want paths on a common host.  Is that what you are looking for?

**Comment by Richard-Mathie** [comment]
Yeah so what I was thinking is that there is now way of setting a location label such that you can route some locations to different services. something like this....

    #/etc/nginx/nginx.conf
    # ... 
    upstream host.domain {
          zone host.domain_backend 64k;
              server 1.2.3.4:3000;
              server 1.2.3.5:3000;
    }
    upstream service.host.domain {
          zone service.host.domain_backend 64k;
              server 1.2.3.6:3000;
              server 1.2.3.7:3000;
    }
    server {
          listen 80;

          server_name host.domain;
        
          location / {
              proxy_pass http://host.domain;
          }
          location /service {
               proxy_pass http://service.host.domain
          }
    }

would that make scene?

**Comment by ehazlett** [comment]
Oh gotcha.  Yes you can do that today (just merged the PR) 

You will want to use the following options: 

- `interlock.context_root`
- `interlock.context_root_rewrite`

See https://github.com/ehazlett/interlock/blob/master/docs/interlock_data.md#context-root for details.

In your example above you should be able to add `--label interlock.context_root=/service` to any container that you want to serve under `/service`.

This will come in the 1.2 release but you can test now with the `ehazlett/interlock:master` image.

**Comment by pbaiz-amey** [comment]
Thanks @ehazlett, we got the context_root working. We will keep experimenting and report back if we find any problems (or have more questions).

**Comment by ehazlett** [comment]
Cool thx. I'm goign to close this out.  Feel free to open another if you run into issues.

**Comment by Richard-Mathie** [comment]
oops looks like the newest master has changed a bit, and seems to be misbehaving a bit. will have to pull and build the old version.

**Comment by ehazlett** [comment]
@Richard-Mathie Please file an issue if you notice something.  You can also use `ehazlett/interlock:master` to check.  That is always built from master.  The latest stable release is `1.1.0`.
