### ISSUE TITLE
Supporting multiple ports

### ISSUE THREAD

**Issue by tombee** [ehazlett/interlock#12]
I'd like to run the official Jenkins docker image: https://registry.hub.docker.com/_/jenkins/

As per the documentation, it needs the following two ports exposed:
 - TCP: 8080 for HTTP 
 - UDP: 50000 for jenkins slaves to connect via swarm

Is this a reasonable use case for interlock?

**Comment by ehazlett** [comment]
As HAProxy does not support UDP, this most likely won't happen any time soon.  TCP support is coming (once Swarm support is finished being tested) and is in the branch https://github.com/ehazlett/interlock/tree/tcp-support if you want to test.

Thanks!
