### ISSUE TITLE
[haproxy] does not seem to play well without volume

### ISSUE THREAD

**Issue by princemaple** [ehazlett/interlock#121]
![screenshot 2016-04-14](https://cloud.githubusercontent.com/assets/1329716/14526456/bda63140-0286-11e6-8f97-c022777b7b69.png)

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 175
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 282
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 995.9 MiB
Name: dev
ID: HQV4:465H:7GQQ:OSLM:JGXA:I4NK:LLCR:7SWV:NDEF:GJQ5:SX6P:D4XR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 29
 Goroutines: 47
 System Time: 2016-04-14T11:20:45.418654104Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by princemaple** [comment]
tested on both the local virtualbox and my ubuntu vps

**Comment by brugnara** [comment]
Having the very same issue here. The log says something about some missing file and in the config.toml, in fact, is in setted different location. Anyway changing that path did not resolved for me.

```
# config.toml: 
ConfigPath = "/usr/local/etc/haproxy.cfg"

# docker-conpose logs haproxy:
Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory

Any help will be appreciated.

ps @princemaple your $PS1 is awesome, where can I find the code? :+1:

**Comment by princemaple** [comment]
`ConfigPath = "/usr/local/etc/haproxy.cfg"` actually needs to be changed to `ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"`, this is where the official haproxy image is looking for the config file. However, after making the change, it still doesn't work for me. @brugnara I'd like to know if, with the change, it works for you.

> your $PS1 is awesome, where can I find the code?

The shell in screenshot is actually inside the boot2docker machine. I use [myboot2docker](https://github.com/wharsojo/myboot2docker) to get zsh and OMZsh, and the prompt is just part of OMZsh. The prompt is called paradox. If you want to use it, you need to get a font that's fixed up for Powerline. I'll attach the font I use.

[Menlo-for-Powerline.zip](https://github.com/ehazlett/interlock/files/219317/Menlo-for-Powerline.zip)

**Comment by brugnara** [comment]
Thank you for sharing.

This is not working at all. I think we need mount the basic haproxy conf. [This esample doesn't even start](https://github.com/ehazlett/interlock/blob/master/docs/extensions/haproxy.md), I think the documentation is very poor for haproxy. Nginx works well. I will try to create a simple haproxy conf and I'll report the result.

**Comment by princemaple** [comment]
FYI @ehazlett I did check in the haproxy container, that the configuration is there. It's just, for some reason, not really working out. One interesting thing was, I couldn't get the container (haproxy_haproxy_1) to ping haproxy_app_1 when running the haproxy example, but it works when pinging haproxy_interlock_1. This is possibly why it's not working...

**Comment by ehazlett** [comment]
@princemaple yes the path is updated in https://github.com/ehazlett/interlock/pull/113

@brugnara i am working on a docs PR to add an entire site for interlock.  This will give much better documentation and usage examples.

Here is an screenshot from what I have been working on (still very much a WIP):

![2016-04-14-125935_2636x1459_scrot](https://cloud.githubusercontent.com/assets/260642/14536520/ce5a96f2-0240-11e6-87eb-6b64245a8aab.png)


As for the restart issue, I'm working on an improvement to the restart logic to ensure all proxy containers are properly restarted.

**Comment by princemaple** [comment]
Thanks for sharing the information!

**Comment by ehazlett** [comment]
You are most welcome and thanks for the feedback and for using it :)

**Comment by ehazlett** [comment]
@princemaple Could you try the ehazlett/interlock:master image?  I have some updates with how it detects and restarts the proxies. I want to see if this fixes your issue.

**Comment by princemaple** [comment]
Hi @ehazlett thanks for the update. I tested it locally in boot2docker with docker 1.11.1 and it works as expected. When I tested the same config on a VPS with Ubuntu 15.10, docker 1.11.1, the haproxy seems to fail to find the backend server and keeps giving me 503. Same problem (well, similar, 502) happened when I tried Caddy yesterday, I used Caddy to replace interlock+haproxy to test its auto https feature, and it just gave 502; again it worked perfectly locally. Now I'm starting to think maybe something is wrong with my VPS config.

**Comment by princemaple** [comment]
Actually, I was simply being stupid :)
It's returning 503 because I didn't change the hostname in the compose file to my staging hostname.

Now I just need to figure out what happened to Caddy...
Interlock is all good :) Thanks @ehazlett

**Comment by ehazlett** [comment]
FYI I fixed a bug with the proxy restart logic on master.  You can test with `ehazlett/interlock:master` if you like.  Thanks for the update.  I'll close this for now.
