### ISSUE TITLE
How to set https/tcp stream loadbalancing ?

### ISSUE THREAD

**Issue by keyolk** [ehazlett/interlock#130]
I'm trying to deploy some applications which uses mqtt, coap, tcp, websocket
also it uses http/https.

I follow examples in this repository and confirmed http loadbalacing works well.
and also it can proxy http to https backend.
But I failed to set https to https and other TCP stream loadbalacing.

I cant find any of documents for,
Does someone have any idea how I can solve this ?

**Comment by ehazlett** [comment]
Currently only http is supported.  TCP is on the roadmap but no ETA.
