### ISSUE TITLE
High availability Interlock

### ISSUE THREAD

**Issue by liamawhite** [ehazlett/interlock#132]
When trying to achieve a high availability application with interlock, is the expected deployment to be 'x' interlock containers and 'x' NGINX containers where x is the number of nodes in the swarm? or is it just a single interlock container with a restart policy?

I know the multiple interlock containers setup works as its how my topology currently is set up, but I assume whenever any of the interlock containers detect any events they just overwrite all of the NGINX configuration files?

**Comment by ehazlett** [comment]
There is actually a bit more logic.  Interlock will detect the number of Interlock instances in the Swarm cluster and divide the work of updating amongst each instance.  That is to a) scale better and b) prevent race conditions where multiple interlock instances are writing over all files.

**Comment by ehazlett** [comment]
You can see this in the debug logs as:

`DEBU[0001] calculating restart across interlock nodes: num=5  ext=lb`
