### ISSUE TITLE
Must restart interlock to reload nginx with the overlay network

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#136]
Hi!  First, I've been using the overlay network for a little while and it's great.  I have been running into this problem though where anytime I launch a container into the swarm I have to restart the interlock containers in order for the `nginx.conf` to get updated.

My `config.toml` looks like this:

```
ListenAddr = ":8080"
DockerURL = "x.x.x.x:3376" # Swarm manager
TLSCACert = "/certs/ca.pem"
TLSCert = "/certs/server.pem"
TLSKey = "/certs/server-key.pem"

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/etc/nginx/nginx.pid"
MaxConn = 1024
Port = 80
```

and I launch 3 interlock containers with this command

```
docker run \
    --net=mynet \
    -e "constraint:node!=mongo*" \
    -e "affinity:container!=interlock-*" \
    -d \
    --name=interlock-X \
    -v /etc/docker:/certs:ro \
    -v /home/ubuntu/config.toml:/etc/config.toml \
    ehazlett/interlock:master \
    -D run -c /etc/config.toml
```

and I also launch 3 nginx containers like this

```
docker run \
    -d \
    -p 80:80 \
    -p 443:443 \
    --net=mynet \
    --name=nginx-X \
    -e "constraint:node!=mongo*" \
    -e "affinity:container!=nginx-*" \
    --label interlock.ext.name=nginx \
    --label interlock.network=mynet \
    nginx:latest \
    nginx -g "daemon off;" -c /etc/nginx/nginx.conf
```

Then I can launch a container into the swarm

```
docker run --detach \
  --name=docker \
  --net=mynet \
  -e "constraint:node!=mongo*" \
  --label interlock.network=mynet \
  --label interlock.hostname=docker \
  --label interlock.domain=local \
  --label interlock.network=mynet \
  ehazlett/docker-demo
```

This will start the container properly but I have to run `docker restart interlock-0 interlock-1 interlock-2` before it becomes available publicly.

I'm hosted on AWS and have the following ports open:

tcp/3376
tcp/80
tcp/8080
tcp/22
udp/7946
tcp/2376
tcp/7946
tcp/2375
udp/4789
tcp/8500

These are all available from anywhere.  

I think I have a problem with my `config.toml` but I'm not sure.  Thanks in advance!

EDIT:
I have also tried 

```
ListenAddr = "interlock-X:8080"  # allow overlay to give the address
DockerURL = "x.x.x.x:3376" # Swarm manager
TLSCACert = "/certs/ca.pem"
TLSCert = "/certs/server.pem"
TLSKey = "/certs/server-key.pem"

...
```

It didn't break it any further but it also didn't help.

**Comment by ehazlett** [comment]
I've seen this happen when the event stream becomes unstable from Swarm.  Can you try restarting your Swarm manager and interlock (after restarting Swarm) and see if the issue persists?

FWIW I have a working branch to at least warn when events aren't seen.  It's not perfect but would at least give warning.

**Comment by krishamoud** [comment]
Wow!  That worked perfectly.  Thanks!

**Comment by krishamoud** [comment]
Quick question, what could/would cause the event stream to become unstable?

**Comment by ehazlett** [comment]
I'm not sure. I'll ping the swarm team to see if they have any ideas.
