### ISSUE TITLE
Missing documentation for `interlock.network` label

### ISSUE THREAD

**Issue by LAndreas** [ehazlett/interlock#137]
I played with interlock and 'Docker for Mac' + docker-compose. To make this work I needed to use the undocumented `interlock.network` label (I found it in the source). This worked great for me and I was wondering why this label is not documented. Is there any reason for this?

**Comment by tpbowden** [comment]
Out of interest what is it for?

**Comment by ehazlett** [comment]
ugh looks like this was lost in a commit.  i will add it.

@tpbowden this is for using the Docker overlay network instead of exposing externally accessible ports.

**Comment by ehazlett** [comment]
fixed in cef2526
