### ISSUE TITLE
Remote ip not resolved correctly after haproxy

### ISSUE THREAD

**Issue by taiman77** [ehazlett/interlock#14]
When using interlock and haproxy remote ip cannot be resolved correctly. Example in PHP code
["REMOTE_ADDR"] return proxy IP (example 172.17.42.1)
["HTTP_X_FORWARDED_FOR"] return docker host internal id in my case it is 192.168.1.200
even http heade cannot give correct ["HTTP_X_FORWARDED_FOR"] gives again docker host internal ip 192.168.1.200

Expexted result should be that client real IP is resolved.

**Comment by ManMohanVyas** [comment]
From the interlock documentation:

**backend_options: specify a list of additional options for the backend ({"backend_options": ["forceclose", "http-no-delay"]}) -- see http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.1 **

Check the related post here 
http://serverfault.com/questions/331079/haproxy-and-forwarding-client-ip-address-to-servers


Hope this will help :)

**Comment by ehazlett** [comment]
Actually I believe this is already fixed. Could you try the latest version
and confirm it's working?  Thanks!

**Comment by ehazlett** [comment]
Closing as this header should be added in the latest version.  Please re-open if needed.
