### ISSUE TITLE
adding custom options to template

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#142]
is there anyway to add some custom options to the nginx config for each container?
for instance i need an "add_header" option for each container to add some Access-Control-Allow-* options. 

thanks!

**Comment by chromerobv** [comment]
sorry should have been more specific i need to allow  CORS requests to the containers.

**Comment by princemaple** [comment]
this functionality seems to be covered by https://github.com/ehazlett/interlock/pull/124 already?

**Comment by princemaple** [comment]
unless you want per-container configuration

**Comment by chromerobv** [comment]
yup thanks!
