### ISSUE TITLE
make build

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#143]
had some problems with make build. first it looks like it is missing some repos

i.e.
```
clone git github.com/hashicorp/go-cleanhttp master
clone git github.com/matttproud/golang_protobuf_extensions master
clone git github.com/ehazlett/ttlcache master
```

once i take care of making sure those exist i get 
```
# make build
# github.com/ehazlett/interlock/ext/lb
../../ext/lb/lb.go:375: l.client.CopyToContainer undefined (type *dockerclient.DockerClient has no field or method CopyToContainer)
make: *** [build-static] Error 2
```

**Comment by ehazlett** [comment]
I would suggest to build from the container.  It has the proper vendored dependencies and uses a default build environment.  You can use `make build-container`.
