### ISSUE TITLE
interlock doesn't reload proxy if it comes up after everything

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#144]
so while testing everything out i came across a scenario where if i have everything running and then destroy my nginx proxy and start a new one, interlock will notice a proxy has come up and will not reload its config. i have to restart interlock for it to work. 

i'm not sure if this is by design but i would think if a proxy comes up and interlock sees it, it should reload its config instantly.

**Comment by ehazlett** [comment]
hmm ok this might be a bug. i'll investigate.  thx for reporting!

**Comment by everett-toews** [comment]
There's a fix for this bug in my multi-interlock config PR at https://github.com/ehazlett/interlock/pull/123/files#diff-080cac5c72ef5c53a6cc07f1d4c8a15aL466

**Comment by chromerobv** [comment]
great! nice work!

**Comment by ehazlett** [comment]
I just checked this in master and it's working fine.  Can you please try the latest (`ehazlett/interlock:1.1.1`) and see if it persists?  Thanks!
