### ISSUE TITLE
Interlock Nginx config loading... config not found

### ISSUE THREAD

**Issue by tomskip123** [ehazlett/interlock#146]
I've tried the newest docker-compose file with the 1.1.0 version, and i'm getting an error /etc/interlock/config.toml do i have to mount it myself?

I'm testing it on an amazon ec2 if that makes a difference.

**Comment by everett-toews** [comment]
Yep. And the docker-compose.yml file already [does that for you](https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx/docker-compose.yml#L7).

```bash
$ git clone https://github.com/ehazlett/interlock.git
$ cd interlock/docs/examples/nginx/
$ docker-compose up
Creating nginx_interlock_1
Creating nginx_app_1
Creating nginx_nginx_1
Attaching to nginx_interlock_1, nginx_app_1, nginx_nginx_1
...
```

**Comment by tomskip123** [comment]
yeah... i was executing the file in the command which was overriding my environment variable. Thanks
