### ISSUE TITLE
haproxy fails to startup: Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg

### ISSUE THREAD

**Issue by demaniak** [ehazlett/interlock#147]
How to reproduce:

- Clone this repo
- cd into `docs/examples/haproxy`folder
- run `docker-compose up`

It might be that I missed something?

**Comment by demaniak** [comment]
The nginx example works fine.

**Comment by ehazlett** [comment]
Hmm maybe something changed with the image.  I'll see if I can reproduce.  Thanks for reporting!

**Comment by ehazlett** [comment]
Ok I've made some updates to the examples and this works for me.  You will still notice the error as the HAProxy official image does not ship with a default config file however Interlock will generate upon start and create one for HAProxy.  It will then restart the container and it should start.  Please re-open if you continue to have issues.  Thanks!

**Comment by demaniak** [comment]
ah ok!

I tried it earlier today - was still broken, but before I could comment here, had to run out to a meeting.

JUST tried master now, seems to be coming up as detailed.

Thank you @ehazlett !

**Comment by ehazlett** [comment]
Yw. Thanks!
