### ISSUE TITLE
How I can do session stickiness with interlock

### ISSUE THREAD

**Issue by ManMohanVyas** [ehazlett/interlock#15]
How session stickiness work with interlock?? Is it default configured ?? 
And what about changing the algorithm. I cant see any good documentation on the how to use things.
If you can create one that will be of great use.

I can prepare one. If you can give basic guidline.

Regards,
ManMohan Vyas

**Comment by ehazlett** [comment]
Interlock uses HAProxy underneath.  We currently do not do anything with
stickiness or the algorithm (feel free to open an issue separately if you
would like to see them).  Interlock is pretty basic as it just writes the
config -- docs are light but cover the features (
https://github.com/ehazlett/interlock#interlock).

**Comment by ManMohanVyas** [comment]
I have closed this issue. Creating a new issue as a feature request for Algorithm and session request.
Me too is trying to fix it. We can fix it via getting input from enviornment variables. Completely new to "go". Not even able to compile the project. :(  Will try anyways. 

Thank you
