### ISSUE TITLE
Question about multiple interlock 1.1 containers

### ISSUE THREAD

**Issue by bosiwow** [ehazlett/interlock#150]
I was wondering if I have multiple interlock 1.1 containers running, I don't think it uses a shared db between the containers, or am I wrong?
Does this mean that when there is a new event on the swarm controller, every interlock container should be notified? Isn't that inefficient?

**Comment by ehazlett** [comment]
It's slightly smarter than that.  We inspect the Swarm cluster and calculate the number of Interlock containers.  Each Interlock container takes a slice of the proxy containers to restart and then divides the work. https://github.com/ehazlett/interlock/blob/master/ext/lb/lb.go#L441
