### ISSUE TITLE
Interlock fails to startup: level=fatal msg="read /etc/interlock/config.toml: is a directory"

### ISSUE THREAD

**Issue by ksketo** [ehazlett/interlock#159]
I am trying to run the haproxy example. Both the haproxy and interlock image fail to startup. Interlock fails with: 

`level=fatal msg="read /etc/interlock/config.toml: is a directory"`

and haproxy with:

```
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds
[ALERT] 143/173126 (6) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
<5>haproxy-systemd-wrapper: exit, haproxy RC=256
```

When I run `docker-compose up -d interlock` the container starts. However if I remove the container and run the same command, I get the error that config.toml is a directory.

Edit:
I run docker-machine with the digitalocean driver

**Comment by ehazlett** [comment]
Can you give more info on how you are starting this?  Are you doing this remotely and using the bind mount?  If so, Docker will create a directory instead.

**Comment by TheBellman** [comment]
Have hit the same issue. Not happy. Not happy at all. Doing this via docker compose, as illustrated in the documentation at https://github.com/ehazlett/interlock/tree/master/docs/examples/haproxy

```services:
    interlock:
        image: ehazlett/interlock:master
        command: run -c /etc/interlock/config.toml
        ports:
            - "8080"
        volumes:
            - ./config.toml:/etc/interlock/config.toml
            - ./haproxy.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template
            - /var/run/docker.sock:/var/run/docker.sock```

**Comment by ehazlett** [comment]
Can you give more info on your setup?  What is your docker host?  What
version etc?

**Comment by TheBellman** [comment]
Docker version 1.11.1, build 5604cbe
docker-compose version 1.7.1, build 0a9ab35
Self hosted, or rather hosted onto VNetrix VMs running Centos 7

**Comment by ehazlett** [comment]
@ksketo this is the reason. You cannot mount local directories to remote docker hosts. It won't work. Therefore docker is making it a directory on your digital ocean droplet instead of using the file on your local system. You can either use a local docker engine or copy the entire interlock repo to the DO host and run compose on the host itself (via SSH).

**Comment by ehazlett** [comment]
Are you using a remote host or are you local to the docker engine?

**Comment by TheBellman** [comment]
Remote - so that could be the same issue. Will explore it further.

**Comment by ehazlett** [comment]
That is the issue. See the response I sent to @ksketo. I will add a note to
the docs.

**Comment by TheBellman** [comment]
So your examples were all based on local docker swarms? Definitely worth explaining that further, as readers like myself are likely to coming across this when looking for production-like deployments.

**Comment by ehazlett** [comment]
Look in the examples. There are others specifically for Swarm.

**Comment by ksketo** [comment]
@ehazlett yes that was the reason. Thanks for your reply
