### ISSUE TITLE
301 Redirects NGINX

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#160]
Currently there is only one default route and that is to the 503 page.  I was wondering what the thoughts were for other default routes, e.g.

```
server {
    listen 80;
    server_name example.com;
    return 301 http://www.example.com$request_uri;
}
```

This could be useful for redirecting from the naked domain to the `www` domain.

I have a temporary solution which is 
```
docker run -d \
  --label "interlock.hostname=" \
  --label "interlock.domain=example.com" \
  ehazlett/docker-demo
```

but this doesn't seem great because it just creates another web server at the naked domain instead of a simple 301 redirect.

Is there already a way to do what I'm trying to do?  If not I'd be happy to submit a PR for it if this seems useful to anyone else.

**Comment by ehazlett** [comment]
I use the alias domain label which achieves the same thing and reuses the
same containers.

I'm up for others but it gets a bit implementation specific depending on
the usage.

**Comment by krishamoud** [comment]
Yeah that worked exactly as you said.  Thanks!

**Comment by ehazlett** [comment]
:+1:
