### ISSUE TITLE
Interlock does not generate /etc/nginx/nginx.conf for  nginx

### ISSUE THREAD

**Issue by maanenh** [ehazlett/interlock#163]
I am testing with a configuration on Ubuntu 14.04.4 LTS .

Situation is that swarm manager, interlock and nginx are all on the same server.
I tried al lot of different options and different interlock versions. 
Only with version 1.0.1 I got it working. With newer version I got next message in the log

```
DEBU[0360] proxy config path: /etc/nginx/nginx.conf      ext=lb
DEBU[0360] proxyContainers: []                           ext=lb
DEBU[0360] saving proxy config                           ext=lb
WARN[0360] unable to detect interlock node; to ensure optimal reloads make sure interlock is visible in the swarm cluster  ext=lb
DEBU[0360] signaling reload                              ext=lb
DEBU[0361] triggering proxy network cleanup              ext=lb
```

docker-compose file and interlock log are attached

[docker-compose.yml.txt](https://github.com/ehazlett/interlock/files/284229/docker-compose.yml.txt)

[interlock.log.txt](https://github.com/ehazlett/interlock/files/284230/interlock.log.txt)

Can someone help me and tell me what I do wrong

**Comment by ehazlett** [comment]
There was a bug fixed recently that sounds like it would fix this. Can you
try the ehazlett/interlock:1.1.3 image?

**Comment by maanenh** [comment]
I used already the 1.1.3 version. See the docker-compose fragment below

```yaml
services:
  interlock:
    image: ehazlett/interlock:1.1.3
    command: -D run -c /etc/interlock/config.toml
```

**Comment by ehazlett** [comment]
You have to run interlock on the same swarm as the proxy containers otherwise interlock cannot find them to restart.  You can see that it doesn't find any.

**Comment by ehazlett** [comment]
Next time please paste inline.

**Comment by maanenh** [comment]
Thanks for the quick response. 
I deployed the interlock container now on the docker-swarm and it works.
I followed the 'tutorial' at https://docs.docker.com/swarm/swarm_at_scale/deploy-app/ and in that description interlock was deployed directly on the docker engine

**Comment by ehazlett** [comment]
Hmm ok I will see if we can get that updated.  Sorry!
