### ISSUE TITLE
Haproxy SSL Configuration

### ISSUE THREAD

**Issue by nhester1** [ehazlett/interlock#172]
Interlock successfully configures Nginx for SSL, but using the same parameters for Haproxy leads to connection refused.

Labels I am using in my app:
- 'interlock.ssl=true'
- 'interlock.ssl_only=true'
- 'interlock.ssl_cert=/etc/docker/cert.pem'
- 'interlock.ssl_cert_key=/etc/docker/key.pem'

Interlock Environment Variables:
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/etc/docker/ca.pem"
            TLSCert = "/etc/docker/cert.pem"
            TLSKey =  #"/etc/docker/key.pem"
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/etc/nginx/nginx.pid"
            MaxConn = 1024
            Port = 80
            SSLCertPath = ""
            SSLPort = 443
            User = "www-data"
            WorkerProcesses = 2
            RLimitNoFile = 65535
            ProxyConnectTimeout = 600
            ProxySendTimeout = 600
            ProxyReadTimeout = 600
            SendTimeout = 600
            SSLCiphers = "HIGH:!aNULL:!MD5"
            SSLProtocols = "SSLv3 TLSv1 TLSv1.1 TLSv1.2"

**Comment by ehazlett** [comment]
Check the HAProxy container.  Typically the Docker cert and key will not be
valid for HAProxy.

**Comment by nhester1** [comment]
Is there anyway to make HAProxy behave the same as NGINX with regards to the certs?
