### ISSUE TITLE
Interlock 1.2.0-master complains about "Missing nginx configuration template: file=/etc/interlock/nginx.conf.template"

### ISSUE THREAD

**Issue by garthmbooth** [ehazlett/interlock#173]
I'm using a version of the config.toml and docker-compose.yml files for the nginx-swarm setup here: https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx-swarm 

**I'm seeing the following error when using ehazlett/interlock:master image.** 

time="2016-06-13T17:28:12Z" level=info msg="interlock 1.2.0-master (2fd9af6)"
time="2016-06-13T17:28:12Z" level=error msg="Missing nginx configuration template: file=/etc/interlock/nginx.conf.template" ext=lb
time="2016-06-13T17:28:12Z" level=error msg="Use the TemplatePath option in your Interlock config.toml to set a custom location for the nginx configuration template" ext=lb
time="2016-06-13T17:28:12Z" level=error msg="Examples of an configuration template: url=https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx" ext=lb
time="2016-06-13T17:28:12Z" level=fatal msg="stat /etc/interlock/nginx.conf.template: no such file or directory" ext=lb

**If I use ehazlett/interlock:1.0.0, I DO NOT see this error.**

Here's my config.toml and docker-compose.yml:
ListenAddr = ":8080"
DockerURL = "tcp://10.50.145.1:8333"

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/var/run/nginx.pid"
TemplatePath = "/etc/interlock/nginx.conf.template"
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
NginxPlusEnabled = false

docker-compose.yml: 

interlock:
    image: ehazlett/interlock:1.0.0
    command: run -c /etc/interlock/config.toml
    ports:
        - 8080
    environment:
     - "constraint:node==vagrant-ubuntu-trusty-64"
    volumes:
        - /home/vagrant/config.toml:/etc/interlock/config.toml
        - nginx:/etc/nginx
nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    environment:
     - "constraint:node==vagrant-ubuntu-trusty-64"
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/nginx
web:
    image: wordpress
    links:
     - mysql
    environment:
     - "WORDPRESS_DB_PASSWORD=hpe"
     - "constraint:node==csimebe02-b05"
     - "interlock.hostname=hpeplugin"
     - "interlock.domain=local"
    ports:
     - "8080:80"
mysql:
    image: mysql:latest
    ports:
     - "4306:3306"
    environment:
     - "MYSQL_ROOT_PASSWORD=hpe"
     - "MYSQL_DATABASE=wordpress"
     - "constraint:node==csimebe02-b05"
    volume_driver: hpe
    volumes:
     - 'mysql:/var/lib/mysql'

**Comment by demaniak** [comment]
Hi, I think your problem is that you have to mount the nginx template in with a `volume` directive, same way you are mounting the config.toml in.

**Comment by ekcheu** [comment]
Seeing similar issue on my end.  nginx.conf is not first initially generated unless I use version ehazlett/interlock:1.0.0.  Templating of nginx.conf also does not work.  However, if I simply copy nginx.conf file to a directory locally, and mount it (or generate it initially using ehzlett/interlock:1.1.0), and then stop and then remove the interlock container, and the run the interlock:latest container, things work fine.

I'm using redhat enterprise 7 with firewall rules enabled.  and Selinux enabled as well too (I had to use chcon on the nginx directory in order for docker to be able to write to it).

**Comment by ehazlett** [comment]
Ok there was a change that added these as default that I thought I
reverted. I'll take a look. Thanks for reporting!

**Comment by ehazlett** [comment]
This should be fixed.
