### ISSUE TITLE
Disable caching of Nginx

### ISSUE THREAD

**Issue by cvandome** [ehazlett/interlock#175]
Hello,

For demo purpose, we use Nginx + interlock and we have always a round-robin problem.
As an example, if we have 5 instances of a scaled app, nginx switch only on 2 instances. This result randomly change.
Nginx seem to cache requests, I have seen that in the logs:
2016/06/16 14:27:12 [warn] 14#14: *3882 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/02/0000000021 while reading upstream, client: 192.168.50.1, server: test.local, request: "GET /booking-mvc/resources/dojo/dojo.js HTTP/1.1", upstream: "http://192.168.50.11:32769/booking-mvc/resources/dojo/dojo.js", host: "test.local:8000", referrer: "http://test.local:8000/booking-mvc/"

Is there a way to disable the caching system via Interlock parameters in compose file ?

Thanks !

**Comment by cvandome** [comment]
I have found a workaround, it's the NGINX caching process, not an Interlock problem :)

If you want no cache for demo, dev or testing purpose add this directive with the proxypass in the location zone:
add_header Cache-Control "no-cache, must-revalidate, max-age=0";

Hope it will help someone.

**Comment by ehazlett** [comment]
Thanks for the heads up!
