### ISSUE TITLE
Interlock does not generate nginx.conf

### ISSUE THREAD

**Issue by Cail423** [ehazlett/interlock#176]
enable interlock container command:

docker run -p 8282:8080 \
           -d -ti --name tempinterlock  \
           --link shipyard-swarm-manager \
           -v /tmp/interlock/nginx:/etc/conf  \
           -v /tmp/interlock/config.toml:/etc/interlock/config.toml \
           -v /tmp/interlock/template/nginx.conf.template:/etc/ingterlock/nginx.conf.template  \ 
           ehazlett/interlock:1.2.0 -D run -c /etc/interlock/config.toml

config.toml:

ListenAddr = ":8080"
DockerURL = "tcp://shipyard-swarm-manager:3375"

[[Extensions]]
  Name = "nginx"
  ConfigPath = "/etc/conf/nginx.conf"
  PidPath = "/var/run/nginx.pid"
  TemplatePath = "/etc/interlock/nginx.conf.template"
  MaxConn = 1024
  Port = 80

interlock logs:

INFO[0000] interlock 1.2.0 (cef2526)  
DEBU[0000] loading config from: file=/etc/interlock/config.toml 
DEBU[0000] docker client: url=tcp://shipyard-swarm-manager:3375 
DEBU[0000] loading extension: name=nginx  
DEBU[0000] using configuration template: file=/etc/interlock/nginx.conf.template  ext=lb
INFO[0000] interlock node: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] starting event handling  
INFO[0000] using event stream  
DEBU[0000] event received: status=interlock-start id=0 type= action= 
DEBU[0000] notifying extension: lb  
DEBU[0000] triggering reload                             ext=lb
DEBU[0000] event received: status=create id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957 type=container action=create 
DEBU[0000] notifying extension: lb  
DEBU[0000] event received: status= id= type=network action=connect 
DEBU[0000] notifying extension: lb  
DEBU[0000] inspecting container: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] checking container labels: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] ignoring interlock container: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] event received: status=start id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957 type=container action=start 
DEBU[0000] notifying extension: lb  
DEBU[0000] inspecting container: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] checking container labels: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] ignoring interlock container: id=243500be2a314b324591ccfe217adc1a61c360dc5009440e392493d1fa145957  ext=lb
DEBU[0000] event received: status=kill id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423 type=container action=kill 
DEBU[0000] notifying extension: lb  
DEBU[0004] reaping key: reload  
DEBU[0004] triggering reload from cache                  ext=lb
DEBU[0004] checking to reload                            ext=lb
DEBU[0004] updating load balancers                       ext=lb
DEBU[0004] generating proxy config                       ext=lb
DEBU[0004] websocket endpoints: []                       ext=nginx
DEBU[0004] alias domains: []                             ext=nginx
INFO[0004] mqqstatic.wepiao.com: upstream=10.3.1.228:32843  ext=nginx
DEBU[0004] websocket endpoints: []                       ext=nginx
DEBU[0004] alias domains: []                             ext=nginx
INFO[0004] mqq.wepiao.com: upstream=10.3.1.228:32842     ext=nginx
DEBU[0004] proxy config path: /etc/conf/nginx.conf       ext=lb
DEBU[0004] detected proxy container: id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423 backend=nginx  ext=lb
DEBU[0004] proxyContainers: [{afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423 [/shipyard-manager/mad_babbage] nginx nginx -g 'daemon off;' -c /etc/conf/nginx.conf 1464254203 Up 2 weeks [{10.3.1.116 80 80 tcp} { 443 0 tcp}] 0 0 map[interlock.ext.name:nginx] {map[bridge:{<nil> [] []  301b88ec90f5efe7c77d23a6fd4c8183fc927d1fbcddb763330f536a0357b9f9 172.17.0.1 172.17.0.3 16   0 02:42:ac:11:00:03}]}}]  ext=lb
DEBU[0004] saving proxy config                           ext=lb
DEBU[0004] updating proxy config: id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423  ext=lb
DEBU[0004] event received: status=extract-to-dir id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423 type=container action=extract-to-dir 
DEBU[0004] notifying extension: lb  
DEBU[0004] signaling reload                              ext=lb
DEBU[0005] reloading proxy container: id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423  ext=nginx
INFO[0005] restarted proxy container: id=afe06d572973 name=/shipyard-manager/mad_babbage  ext=nginx
INFO[0005] reload duration: 1078.94ms                    ext=lb
DEBU[0005] event received: status=kill id=afe06d5729736a25b1337c59dcae3039a426a32e3e23bd6eb2a69a312f971423 type=container action=kill 
DEBU[0005] notifying extension: lb

[root@shipyard-manager nginx]# pwd
/tmp/interlock/nginx
[root@shipyard-manager nginx]# ll
total 0

not generate nginx.conf

os : CentOS Linux release 7.2.1511 (Core)
docker : Server Version: 1.11.1

what is worng with me ? pls tell me,thanks.

**Comment by Cail423** [comment]
i use interlock 1.0.0 generate nginx.conf  Ok, but customize nginx template invalid. interlock use default template.

**Comment by demaniak** [comment]
@Cail423 I believe the custom template support is available in interlock 1.2.0

**Comment by Cail423** [comment]
@demaniak  but 1.2.0 not generate nginx.conf ;  I do not know what went wrong , so Recourse

**Comment by Cail423** [comment]
DEBU[0030] triggering reload                             ext=lb
DEBU[0034] reaping key: reload                          
DEBU[0034] triggering reload from cache                  ext=lb
DEBU[0034] checking to reload                            ext=lb
DEBU[0034] updating load balancers                       ext=lb
DEBU[0034] generating proxy config                       ext=lb
DEBU[0034] websocket endpoints: []                       ext=nginx
DEBU[0034] alias domains: []                             ext=nginx
INFO[0034] foo.local: upstream=0.0.0.0:32782             ext=nginx
DEBU[0034] proxy config path: /etc/conf/nginx.conf       ext=lb
DEBU[0034] detected proxy container: id=7513771a231cd907e79a82798c3cc90c4d017c23fead50314415639d898bb35a backend=nginx  ext=lb
DEBU[0034] proxyContainers: [{7513771a231cd907e79a82798c3cc90c4d017c23fead50314415639d898bb35a [/distracted_roentgen] nginx nginx -g 'daemon off;' 1466391915 Up 11 seconds [] 0 0 map[interlock.ext.name:nginx] {map[host:{<nil> [] []  50696c2591b4fdae6531036c495a84e2c2b81ecda5622dea1ec25f6302f79a4b   0   0 }]}}]  ext=lb
DEBU[0034] saving proxy config                           ext=lb
DEBU[0034] updating proxy config: id=7513771a231cd907e79a82798c3cc90c4d017c23fead50314415639d898bb35a  ext=lb
ERRO[0034] error copying proxy config: 404 Not Found: lstat /var/lib/docker/devicemapper/mnt/b1d1126931c7b6ca3cc395d129ea3492f27692007799e654a4c0398f592fee08/rootfs/etc/conf: no such file or directory
  ext=lb
DEBU[0034] signaling reload                              ext=lb
DEBU[0035] reloading proxy container: id=7513771a231cd907e79a82798c3cc90c4d017c23fead50314415639d898bb35a  ext=nginx
INFO[0035] restarted proxy container: id=7513771a231c name=/distracted_roentgen  ext=nginx


ERRO[0034] error copying proxy config: 404 Not Found: lstat /var/lib/docker/devicemapper/mnt/b1d1126931c7b6ca3cc395d129ea3492f27692007799e654a4c0398f592fee08/rootfs/etc/conf: no such file or directory

not not generate nginx.conf , conf not update

**Comment by demaniak** [comment]
@Cail423 apologies, I did not read properly at first! Your setup seems fine as far as I can tell.
But your log output looks like something strange is going on.

Just a stupid question: `-v /tmp/interlock/template/nginx.conf.template:/etc/ingterlock/nginx.conf.template` - seems there is a typo there. Is it just a typo in this issue, or is that really the command line? Because that might be your problem.

**Comment by Cail423** [comment]
My problem has been solved

docker run -P -d -ti --name tempinterlock -v /tmp/interlock/git/interlock/docs/examples/nginx/config.toml:/etc/interlock/config.toml -v /tmp/interlock/git/interlock/docs/examples/nginx/nginx.conf.template:/etc/interlock/nginx.conf.template -v /var/run/docker.sock:/var/run/docker.sock ehazlett/interlock:master -D run -c /etc/interlock/config.toml

nginx.conf.template  add gzip Configuration

Thank you for your attention, please close this issue

**Comment by ehazlett** [comment]
Thanks!
