### ISSUE TITLE
Feature request: To be able to give HA-Proxy algorithm to select from 

### ISSUE THREAD

**Issue by ManMohanVyas** [ehazlett/interlock#18]

**Comment by ManMohanVyas** [comment]
@ehazlett Do you have any specific approch on this?? Was confused along the mixing of algorithm with session stickiness as the very few of them support session stickiness.
For eg: for the algo we take config as **-algo round-robin**
And for sticky we take -sticky true ; then should we match the **algo** to **sticky** flag to get correct combination or we should leave that intelligence to the user ?? and what about the correct spell for the combination should we take a alphabet or short for those ??

Hope was able to explain.

**Comment by ehazlett** [comment]
Thanks for the feedback!  I think instead of trying to error check the algoritms we will just leave it up to the user.

Refs #17

**Comment by ehazlett** [comment]
This is fixed in https://github.com/ehazlett/interlock/commit/8c01696049abc673f55ddb76bb0ef724a1fc662a
