### ISSUE TITLE
Interlock stops working on UCP if a container is running on an unhealthy node

### ISSUE THREAD

**Issue by boydj** [ehazlett/interlock#180]
time="2016-06-28T16:27:09Z" level=error msg="500 Internal Server Error: Container d8250f88fa8dcc4ccd7e84e172fc0f752645baa9cea8591885e80b4ef6b38b66 running on unhealthy node ucp-replica-65784cff.east1a.prod\n" ext=lb

When this occurs nginx will not be configured by interlock for any containers.

**Comment by sjoshi10** [comment]
So this error showed after uninstalling one of the replica nodes. This is what I see after doing "docker ps -a" on the UCP cluster: 
`[ec2-user@ucp-node-577544cd bundle]$ docker ps -a | grep 65784cff
d8250f88fa8d        40fe8a8c618e                                                     "/bin/ucp-tool uninst"   15 hours ago        Host Down                                                                                                             ucp-replica-65784cff.east1a.prod/ucp-phase2
deefd7eb34aa        docker/ucp                                                       "/bin/ucp-tool uninst"   15 hours ago        Host Down                                                                                                             ucp-replica-65784cff.east1a.prod/ucp
5dd49c39de91        docker/ucp-swarm:1.1.1                                           "/swarm join --discov"   4 days ago          Host Down                                                                                                             ucp-replica-65784cff.east1a.prod/ucp-swarm-join
3f73df0f0ccb        docker/ucp-proxy:1.1.1                                           "/bin/run"               4 days ago          Host Down                   10.2.79.95:12376->2376/`

**Comment by ehazlett** [comment]
Can you give some info on your setup?  Docker version, Swarm version, Interlock version, etc?

**Comment by boydj** [comment]
Was just able to reproduce...

$ docker info
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 24
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 mhs-demo0: 192.168.99.101:2376
  └ ID: 5FXQ:OM5C:LMPX:SFPB:UZNV:GWVY:FHNT:O6IL:NKN3:P4CS:TEBU:6Q36
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.12-boot2docker, operatingsystem=Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-07-18T05:35:02Z
  └ ServerVersion: 1.11.2
 mhs-demo1: 192.168.99.102:2376
  └ ID: FZW5:RGJY:GCUH:BPOM:5G73:AZRQ:WNOV:IVD7:XIHB:ZNKC:3LFC:ZDQ4
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.12-boot2docker, operatingsystem=Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-07-18T05:35:35Z
  └ ServerVersion: 1.11.2
 mhs-demo2: 192.168.99.103:2376
  └ ID: UR5T:KLKN:CVIB:RV67:OU24:OGAC:4Z7G:CE7K:HNZ3:GJE2:HKOY:FLNQ
  └ Status: Unhealthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.12-boot2docker, operatingsystem=Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
  └ UpdatedAt: 2016-07-18T05:35:20Z
  └ ServerVersion: 1.11.2
Plugins:
 Volume:
 Network:
Kernel Version: 4.4.12-boot2docker
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 3.063 GiB
Name: cfd028d8810b
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

Here is the compose for the app.

$ cat docker-compose.yml
version: '2'
services:
    web:
        image: dockercloud/hello-world
        ports:
            - 80
        labels:
            interlock.hostname: "test"
            interlock.domain: "local"
        environment:
            - reschedule:on-node-failure
            - affinity:container!=testapp_web_*

Do a docker-compose up -d, stop the node that is running the service. It gets rescheduled but interlock complains about the unhealthy node.

**Comment by ehazlett** [comment]
Are those nodes all managers?

**Comment by boydj** [comment]
Nah, this example is just one manager.

In prod where we saw the issue was with UCP with 1 controller, 2 replicas and 12 nodes.

**Comment by rajarajanpsj** [comment]
We are seeing the same issue when when you the following combination.
Interlock 1.3.0
UCP 2.1.0
Engine 1.13.1-cs2

Any node in the cluster (does not matter whether it is manager or worker) if it is unhealthy, interlock does not update the nginx conf. The error we see is the following.

Error response from daemon: Error response from daemon: Container 3032831d7097de55474d39e55bfdbe18fad2cc8ca070040565fcb1861119e720 running on unhealthy node cdlcldvnd0021

In this case cdlcldvnd0021 was the unhealthy node.

**Comment by ehazlett** [comment]
@rajarajanpsj can you enable debug and give some more logging around the error?  It looks like there is an error coming back from UCP which is causing interlock to not update the config but I'm not sure where it is to handle.

**Comment by rajarajanpsj** [comment]
@ehazlett  In our cluster we do have one of the nodes which is in unhealthy state. But that is under maintenance for some reason. But it is stopping us from deploying to another node (which is not related to that unhealthy node logically)

INFO[0000] interlock 1.3.0 (d617b05)
DEBU[0000] loading config from: file=/etc/interlock/config.toml
DEBU[0000] using tls for communication with docker
DEBU[0000] docker client: url=tcp://ucp.engineering-cdl.es.paascloud.oneadp.com:443
DEBU[0000] loading extension: name=nginx
DEBU[0000] using configuration template: file=/etc/interlock/nginx.conf.template  ext=lb
INFO[0000] interlock node: id=7b2a624059522504dcd1c44bdfb2673f05afc415cb2c9c38eb175442e57f3c4f  ext=lb
DEBU[0000] starting event handling
INFO[0000] using polling for container updates: interval=5s
DEBU[0005] detected new containers; triggering reload
DEBU[0005] event received: status=interlock-restart id=1489770139025790867 type= action=
DEBU[0005] notifying extension: lb
DEBU[0005] triggering reload                             ext=lb
DEBU[0008] reaping key: reload
DEBU[0008] triggering reload from cache                  ext=lb
DEBU[0008] checking to reload                            ext=lb
DEBU[0008] updating load balancers                       ext=lb
DEBU[0008] generating proxy config                       ext=lb
DEBU[0008] websocket endpoints: []                       ext=nginx
DEBU[0008] alias domains: []                             ext=nginx
INFO[0008] guardrails.dit.paascloud.oneadp.com: upstream=11.16.44.82:32793  ext=nginx
DEBU[0013] proxy config path: /etc/nginx/nginx.conf      ext=lb
DEBU[0013] detected proxy container: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433 backend=nginx  ext=lb
DEBU[0013] proxyContainers: [{7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433 [/cdlcldvmg0017/interlockconfig_nginx_1] dtr.cdl.es.ad.adp.com/paas/nginx:1.11.1 sha256:d29b0bc44f335b8f4fd412f658541254eefafa1dd8dab77fbeea173a560674cd nginx -g 'daemon off;' -c /etc/nginx/nginx.conf 1489770131 [{ 443 0 tcp} {11.16.43.128 80 80 tcp}] 0 0 map[interlock.ext.name:nginx com.docker.compose.config-hash:d853dd963915d8f5fd06d28301b7fdff791c5517280ac42340e804b654dcbbc3 com.docker.compose.container-number:1 com.docker.compose.oneoff:False com.docker.compose.project:interlockconfig com.docker.compose.service:nginx com.docker.compose.version:1.9.0dev] running Up 14 seconds {interlockconfig_default} 0xc82001e028 []}]  ext=lb
DEBU[0013] saving proxy config                           ext=lb
DEBU[0013] updating proxy config: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433  ext=lb
DEBU[0018] signaling reload                              ext=lb
DEBU[0019] reloading proxy container: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433  ext=nginx
INFO[0019] restarted proxy container: id=7644626835ed name=/cdlcldvmg0017/interlockconfig_nginx_1  ext=nginx
INFO[0019] reload duration: 10812.43ms                   ext=lb
DEBU[0070] detected new containers; triggering reload
DEBU[0070] event received: status=interlock-restart id=1489770204006589439 type= action=
DEBU[0070] notifying extension: lb
DEBU[0070] triggering reload                             ext=lb
DEBU[0074] reaping key: reload
DEBU[0074] triggering reload from cache                  ext=lb
DEBU[0074] checking to reload                            ext=lb
DEBU[0074] updating load balancers                       ext=lb
DEBU[0074] generating proxy config                       ext=lb
DEBU[0074] websocket endpoints: []                       ext=nginx
DEBU[0074] alias domains: []                             ext=nginx
INFO[0074] guardrails.dit.paascloud.oneadp.com: upstream=11.16.44.82:32794  ext=nginx
DEBU[0078] proxy config path: /etc/nginx/nginx.conf      ext=lb
DEBU[0078] detected proxy container: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433 backend=nginx  ext=lb
DEBU[0078] proxyContainers: [{7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433 [/cdlcldvmg0017/interlockconfig_nginx_1] dtr.cdl.es.ad.adp.com/paas/nginx:1.11.1 sha256:d29b0bc44f335b8f4fd412f658541254eefafa1dd8dab77fbeea173a560674cd nginx -g 'daemon off;' -c /etc/nginx/nginx.conf 1489770131 [{ 443 0 tcp} {11.16.43.128 80 80 tcp}] 0 0 map[com.docker.compose.config-hash:d853dd963915d8f5fd06d28301b7fdff791c5517280ac42340e804b654dcbbc3 com.docker.compose.container-number:1 com.docker.compose.oneoff:False com.docker.compose.project:interlockconfig com.docker.compose.service:nginx com.docker.compose.version:1.9.0dev interlock.ext.name:nginx] running Up About a minute {interlockconfig_default} 0xc82001e118 []}]  ext=lb
DEBU[0078] saving proxy config                           ext=lb
DEBU[0078] updating proxy config: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433  ext=lb
DEBU[0083] signaling reload                              ext=lb
DEBU[0084] reloading proxy container: id=7644626835ed500719c50305f98e9b51b5634012ff6ac8745a677fb6c747c433  ext=nginx
INFO[0084] restarted proxy container: id=7644626835ed name=/cdlcldvmg0017/interlockconfig_nginx_1  ext=nginx
INFO[0084] reload duration: 10302.49ms                   ext=lb
DEBU[0430] detected new containers; triggering reload
DEBU[0430] event received: status=interlock-restart id=1489770564058649325 type= action=
DEBU[0430] notifying extension: lb
DEBU[0430] triggering reload                             ext=lb
DEBU[0434] reaping key: reload
DEBU[0434] triggering reload from cache                  ext=lb
DEBU[0434] checking to reload                            ext=lb
DEBU[0434] updating load balancers                       ext=lb
DEBU[0434] generating proxy config                       ext=lb
DEBU[0434] websocket endpoints: []                       ext=nginx
DEBU[0434] alias domains: []                             ext=nginx
INFO[0434] guardrails.dit.paascloud.oneadp.com: upstream=11.16.44.82:32794  ext=nginx
ERRO[0438] Error response from daemon: Error response from daemon: Get https://11.16.45.168:12376/containers/01f2fedf9bdb457da95355489b69cba2ccc811edad0c754cd5036fb7b10e42f8/json: dial tcp 11.16.45.168:12376: getsockopt: connection refused  ext=lb
DEBU[0440] detected new containers; triggering reload
DEBU[0440] event received: status=interlock-restart id=1489770574001438830 type= action=
DEBU[0440] notifying extension: lb
DEBU[0440] triggering reload                             ext=lb
DEBU[0444] reaping key: reload
DEBU[0444] triggering reload from cache                  ext=lb
DEBU[0444] checking to reload                            ext=lb
DEBU[0444] updating load balancers                       ext=lb
DEBU[0444] generating proxy config                       ext=lb
ERRO[0444] Error response from daemon: Error response from daemon: Container 58510723b7daaf46de9b3a1558c9f94964468d776eb23f479b372e3ce89a1110

**Comment by ehazlett** [comment]
@rajarajanpsj can you try version `1.3.1`? I think it should fix this issue.  `ehazlett/interlock:1.3.1` on the docker hub.

**Comment by rajarajanpsj** [comment]
@ehazlett 1.3.1 has resolved this issue!

**Comment by ehazlett** [comment]
awesome.  thanks for the update.  i will tag 1.3.1 to `latest` later tonight.  closing this issue.
