### ISSUE TITLE
Question: How much memory should be allocated for interlock?

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#187]
I currently run a 21 node cluster with interlock running on 3 of the nodes.  The running stats of interlock at any given time are around 2.3MB idle.  In the upcoming months my team will be deploying multiple microservices between 10-15x daily all of which will be managed by interlock.  I have never run into performance/memory issues with interlock but I put memory constraints on ever container in the cluster.

What amount of memory is appropriate for interlock? Would 10MB be sufficient?  That would be about 4x more memory that it uses when it's idle.

Thanks in advance,
-Kris

**Comment by ehazlett** [comment]
Interlock doesnt' need much.  10-20 MB should be sufficient as it's pretty small.
