### ISSUE TITLE
do i need to setup key/value store to be able to add multi-host network?

### ISSUE THREAD

**Issue by virtuman** [ehazlett/interlock#188]
I'm trying to understand if on Docker 1.12 with swarm - do i need to configure a key/value store like etc/consul/zookeeper or is that no longer needed with swarm on 1.12? i was under the impression that it does all of it on it's own after docker swarm init and docker join commands ?

so on a brand new 3-node cluster I followed all steps but the overlay network gets created in a single node (on manager node) only and when i scale service tasks - it doesn't seem like other hosts are getting picked up by the haproxy that gets deployed on manager node.

could you elaborate on what i'm missing, whether it is a key-value store or something else that i need to do for things to work properly on swarm 1.12 ?

thank you

**Comment by virtuman** [comment]
upgrade docker to rc4 and network started to work but now ports don't get exposed anymore

**Comment by ehazlett** [comment]
No kv is needed. The network only shows on a node when a task is scheduled
on that node that needs the network.
