### ISSUE TITLE
[Question] Swarm Cluster + one interlock and multiple app containers with different hostnames + TLD (?)

### ISSUE THREAD

**Issue by danielsand** [ehazlett/interlock#195]
Hello ehazlett,

we're currently evaluating building a new docker pipeline and trying out a bunch of scenarios.

currently we have one docker-compose.yml where all of our containers get deployed + interlock and nginx over SWARM to provide a soft LB for our dockerized application.

all works fine with one set of

test01:
    image: test/demoapp1
   hostname: test01.local
   expose:
      - 8080
    networks:
      - subnet-01
    restart: on-failure:10
    labels:
     interlock.hostname: "test01"
     interlock.domain: "local"

works - can reach test01.local with the browser without problems also scalling up - all the things.

  test01:
    image: test/demoapp1
    hostname: test01.local
    expose:
      - 8080
    networks:
      - subnet-01
    restart: on-failure:10
    labels:
     interlock.hostname: "test01"
     interlock.domain: "local"

test02:
    image: test/demoapp2
     hostname: test02.local
    expose:
      - 8080
    networks:
      - subnet-01
    restart: on-failure:10
    labels:
     interlock.hostname: "test02"
     interlock.domain: "local"

test01.local works as expected.
test02.local not - there is no nginx snippet generated inside the nginx container. 
demoapp02 app is running an reachable

is this supported ? or im missing somewhere something ?

**Comment by ehazlett** [comment]
Are you sure you are using Swarm?  Interlock must be configured to use
Swarm or it cannot see all containers nor events.  This is usually the
problem.

**Comment by danielsand** [comment]
@ehazlett we use swarm but will check again if something is off - thanks

**Comment by danielsand** [comment]
@ehazlett we forgot to specifiy in the docker-compose.yml the ports
only expose - make sense - doesnt do the trick.

thanks :)

**Comment by ehazlett** [comment]
yw!
