### ISSUE TITLE
Error in executing Interlock+HAproxy

### ISSUE THREAD

**Issue by pratapnanda** [ehazlett/interlock#196]
I have created my cluster using DDC-AWS CFN template and then I have pointing my docker toolbox to AWS .I have successfully installed frontend, backend ,MongoDB  application in my cluster .While executing the interlock+Ha proxy ,I have faced below errors .I have used same YML & toml files given here .I don't understand where something I missed from my side.

**Interlock error:** 

time="2016-08-17T14:15:18Z" level=info msg="interlock 1.2.0-master (2fd9af6)" 
time="2016-08-17T14:15:18Z" level=fatal msg="read /etc/interlock/config.toml: is a directory" 

**Haproxy error:** 

<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
[ALERT] 229/141615 (6) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
<5>haproxy-systemd-wrapper: exit, haproxy RC=256

**Comment by mbentley** [comment]
Sorry, I haven't done a great job of keeping these examples up to date.  I'd suggest checking out the reference architecture that covers this on DDC as it stands today: http://success.docker.com/Datacenter/Apply/Reference_Architecture%3A_Service_Discovery_and_Load-Balancing_with_Docker_Universal_Control_Plane_(UCP)#3._External_Service_Discovery_.2B_Load_Distribution

**Comment by pratapnanda** [comment]
@mbentley -Many thanks for above information.Interlock+nginx is working perfect .

Here I am trying to implement interlock+haproxy . First .I choose 1 dedicate UCP node and trying to install interlock+haproxy using docker-compose but it has error like (Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory)

**i am thinking that Interlock support haproxy or not** 

I have checked both below compose file
version : "2"
services:

  interlock:

    image: ehazlett/interlock:1.0.0
    command: -D run --discovery etcd://192.168.23.129:2376 --discovery-tls-ca-cert /kvcerts/ca.pem --discovery-tls-cert /kvcerts/cert.pem --discovery-tls-key /kvcerts/key.pem
    volumes:
        - ucp-node-certs:/certs
        - ucp-node-certs:/kvcerts
        - haproxy:/usr/local/etc/haproxy
    network_mode: "bridge"
    restart: always
  haproxy:

    image: haproxy
    ports:
        - 80:80
        - 443:443
    labels:
        - "interlock.ext.name=haproxy"
    volumes:
        - haproxy:/usr/local/etc/haproxy
    depends_on:
        - interlock
    network_mode: "bridge"
    restart: always
volumes:
  haproxy:
  ucp-node-certs:
     external: true

2nd one -
version : "2"

services:
 interlock:
    image: ehazlett/interlock:1.1.0
    command: run -c /bin/config.toml
    volumes:
        - ucp-node-certs:/certs
        - ./config.toml:/bin/config.toml
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always

 haproxy:
    image: haproxy:latest
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=haproxy"
    restart: always
    depends_on:
        - interlock
volumes:
  ucp-node-certs:
    external: true

config.toml:
ListenAddr = ":8080"
DockerURL = "unix:///var/run/docker.sock"

[[Extensions]]
Name = "haproxy"
ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
PidPath = "/var/run/haproxy.pid"
TemplatePath = ""
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
AdminUser = "admin"
AdminPass = "interlock"

**Comment by ehazlett** [comment]
This is an old version of Interlock and it had some issues with the local Swarm volumes.  Try upgrading to the latest -- it uses a different method to get the configs to the proxy containers.
