### ISSUE TITLE
Interlock is ignoring services with no ports

### ISSUE THREAD

**Issue by groyee** [ehazlett/interlock#198]
I must be missing something here but I really don't understand why Interlock doesn't add a new docker containers when it has no exposed ports?

All I am trying to do is to get the IP addresses of containers running with a specific name.

Is that how it suppose to be by design? Why?

Maybe there is some other solution that I am not aware of? How else can I discover the address of my containers in a distributed swarm cluster with an overlay network?

Thanks.

**Comment by ehazlett** [comment]
What version of Docker are you using?

**Comment by groyee** [comment]
1.12

**Comment by ehazlett** [comment]
Interlock isn't compatible with 1.12 services yet. There is a wip branch
for that. See https://github.com/ehazlett/interlock/pull/186

**Comment by groyee** [comment]
Thanks!
