### ISSUE TITLE
Interlock + NGINX 502

### ISSUE THREAD

**Issue by nhester1** [ehazlett/interlock#201]
If Interlock and NGINX are running on the same node as an application in UCP that application will experience a 502 Bad Gateway. If NGINX and Interlock are moved to a new node the problem stops. The problem occurs for all of our applications. We are running NGINX 1.11.4 and Interlock 1.2.0. We also experience the issue with NGINX 1.11.3 and Interlock 1.1.3. We didn't experience this issue until a few days ago and it only occurs in our Non Production cluster. The only difference that we can see between the Production and Non Production cluster is that the Non Production cluster has engine version 1.11.2-cs5, build d364ea1 and the Production cluster has engine version 1.11.2-cs4, build 7d4e626.

**Comment by mbentley** [comment]
Do you have any custom Docker daemon arguments in use (e.g. - `userland-proxy=false`)?

**Comment by nhester1** [comment]
No, we are running pretty vanilla based on the UCP in production guide.

**Comment by ehazlett** [comment]
Can you paste the logs from the interlock container(s)?

**Comment by nhester1** [comment]
I'll shoot you an email with the logs.

**Comment by ehazlett** [comment]
Nothing from the logs looks abnormal.  I'll stand up a 1.11.2-cs5 and see if I can reproduce.  Can you give an example of what you are deploying?

**Comment by nhester1** [comment]
We are mostly using anapsix/alpine-java:8_jdk_unlimited with Spring Boot apps that have embedded tomcat servers. The labels look roughly like the following:

    - 'interlock.hostname=myapp'
    - 'interlock.domain=mydomain.com'
    - 'interlock.ssl=true'
    - 'interlock.ssl_only=true'
    - 'interlock.ssl_cert=/etc/docker/cert.pem'
    - 'interlock.ssl_cert_key=/etc/docker/key.pem'
    - 'com.docker.swarm.reschedule-policies=["on-node-failure"]' 

The only change I have made to the nginx.conf.template is the addition of:

    proxy_pass_request_headers      on;
    underscores_in_headers on;

Our interlock + nginx compose file looks like this:

interlock:
    image: our.docker.repo/dckrucp/our-interlock:1.0
    command: -D run
    tty: true
    ports:
        - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/etc/docker/ca.pem"
            TLSCert = "/etc/docker/cert.pem"
            TLSKey = "/etc/docker/key.pem"

            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/etc/nginx/nginx.pid"
            TemplatePath = "/etc/interlock/nginx.conf.template"
            MaxConn = 1024
            Port = 80
            SSLCertPath = ""
            SSLPort = 443
            User = "www-data"
            WorkerProcesses = 2
            RLimitNoFile = 65535
            ProxyConnectTimeout = 600
            ProxySendTimeout = 600
            ProxyReadTimeout = 600
            SendTimeout = 600
            SSLCiphers = "HIGH:!aNULL:!MD5"
            SSLProtocols = "SSLv3 TLSv1 TLSv1.1 TLSv1.2"
    volumes:
        - ucp-node-certs:/etc/docker
    labels:
        - 'com.docker.swarm.constraints=["node==mynode..com"]'
    restart: always

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
        - 443:443
    volumes:
        - ucp-node-certs:/etc/docker
    labels:
        - "interlock.ext.name=nginx"
        - 'com.docker.swarm.constraints=["node==mynode.mydomain.com"]'
    restart: always

The issue also seems to occur when using the interlock directly from docker hub.

**Comment by ehazlett** [comment]
Ok.  Can you paste the logs from the nginx containers as well?

**Comment by nhester1** [comment]
Sent you an email with the logs.

**Comment by nhester1** [comment]
We ave just discovered the issue is happening in our cluster that has CS4 as well, so it doesn't appear to be the docker engine version.

**Comment by ehazlett** [comment]
Can you try the latest [release](https://github.com/ehazlett/interlock/releases/tag/v1.3.0) to see if you are still having this issue?  `ehazlett/interlock:1.3.0` -- thanks!

**Comment by ehazlett** [comment]
Closing as this is old.  Please re-open if you continue to have issues.  Thanks!
