### ISSUE TITLE
invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by primehaxor** [ehazlett/interlock#203]
NFO[0700] service01.lab r: upstream=172.21.72.243:32795  ext=nginx
DEBU[0700] websocket endpoints: []                       ext=nginx
DEBU[0700] alias domains: []                             ext=nginx
INFO[0700] service02.lab: upstream=172.21.70.101:32788  ext=nginx
DEBU[0700] websocket endpoints: []                       ext=nginx
DEBU[0700] alias domains: []                             ext=nginx
INFO[0700] service03.lab: upstream=172.21.69.243:32785  ext=nginx
DEBU[0700] websocket endpoints: []                       ext=nginx
DEBU[0700] alias domains: []                             ext=nginx
INFO[0700] service04.lab: upstream=172.21.69.87:32783  ext=nginx
ERRO[0700] invalid character 'N' looking for beginning of value  ext=lb
DEBU[0701] event received: status=top id=1ca6920db6784d25242492609e76fa4dd409f98280cb9912e1122f7d3fb0fb2a type=container action=top 
DEBU[0701] notifying extension: lb  
DEBU[0701] event received: status=top id=1ca6920db6784d25242492609e76fa4dd409f98280cb9912e1122f7d3fb0fb2a type=container action=top 
DEBU[0701] notifying extension: lb     

After that the interlock stopped to work and i have to stop all my containers and start it again, its possible at least know which container is causing that? I have about 50 containers to find which one is causing that.

The nginx.conf looks okay for me with the correct containers ports and hostname

**Comment by ehazlett** [comment]
What version of Docker are you using?

**Comment by ehazlett** [comment]
Closing as this has stagnated.  Please re-open if you continue to have issues.  Thanks!
