### ISSUE TITLE
Feature request: support mutiple upstream for the same container

### ISSUE THREAD

**Issue by o3o3o** [ehazlett/interlock#205]
this is the nginx.conf: 

```
upstream master{
  server container1: 13000
}
upstream slave{
  server container1: 13010
  server container1: 13011
}
server {
  localtion /master {
    proxy_pass http://master
    # other settings
  } 
   localtion /slave {
     proxy_pass http://slave
    # other settings
  } 
}
```

When I try to write the myself nginx.conf.template, I dont't know how to set $host.Upstream.Servers.port.  
So I think it may be handled in logic that handle docker events.

**Comment by ehazlett** [comment]
You can use the same containers for multiple sites.  You can use the `interlock.alias_domain` label (https://github.com/ehazlett/interlock/blob/master/docs/interlock_data.md#alias-domains).  I think that's what you are trying to do.  If not, please re-open.  Thanks!
