### ISSUE TITLE
Can i use my own nginx configuration within interlock 

### ISSUE THREAD

**Issue by viveky4d4v** [ehazlett/interlock#207]
I have a swarm cluster , it consists of two nginx already which is doing all the stuffs . If i implement interlock is there any way that i can use the nginx configuration within the interlock container ?

**Comment by ehazlett** [comment]
Yes. You can turn it into a template that interlock can use. Here is an
example
https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx/nginx.conf.template.example
