### ISSUE TITLE
interlock version 1.3.0 cannot listen swarm

### ISSUE THREAD

**Issue by auzty** [ehazlett/interlock#213]
this is my situation : 
i have 3 server that has docker installed
i'm using docker server / client using this version
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

for standalone swarm, i  set it like this : 

### Server1 : as a swarm master & consul only
**/etc/default/docker**
```
DOCKER_OPTS="-H tcp://172.16.1.1:8000 -H unix:///var/run/docker.sock --storage-driver=aufs"
```
and running consul with : 
```bash
docker run -d --name=consul -p 172.16.1.1:8300:8300 -p 172.16.1.1:8400:8400 -p 172.16.1.1:8500:8500 -p 172.16.1.1:8301:8301 -p 172.16.1.1:8302:8302 progrium/consul -server -node swarm-master -bootstrap-expect 1 -advertise 172.16.1.1
```

running swarm with:
```bash
docker run -d --name=swarm -p 172.16.1.1:2375:2375 swarm:1.1.0 manage --replication --advertise 172.16.1.1:2375 --discovery-opt kv.path=docker/nodes consul://172.16.1.1:8500
```

### Server2 : as node 

**/etc/default/docker**
```
DOCKER_OPTS=" --label nama=main -H unix:///var/run/docker.sock -H 0.0.0.0:2375 --cluster-store=consul://172.16.1.1:8500 --cluster-advertise=172.16.1.200:2375"
```

### Server3 : as node 

**/etc/default/docker**
```
DOCKER_OPTS="--label nama=anak -H unix:///var/run/docker.sock -H 0.0.0.0:2375 --cluster-store=consul://172.16.1.1:8500 --cluster-advertise=172.16.1.201:2375
```

-----

**docker info** from **Server 1**

```
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 55
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 master: 172.16.1.200:2375
  └ Status: Healthy
  └ Containers: 18
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 440 MiB / 1.019 GiB
  └ Labels: executiondriver=<not supported>, kernelversion=3.13.0-98-generic, nama=main, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2017-03-22T11:09:06Z
 minion1: 172.16.1.201:2375
  └ Status: Healthy
  └ Containers: 8
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: executiondriver=<not supported>, kernelversion=3.13.0-98-generic, nama=anak, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2017-03-22T11:09:00Z
Plugins: 
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 3.13.0-100-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.038 GiB
Name: 861240efb93f
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false
```

i run using this command
```bash
#Server 1
docker run -p 8000 -e "constraint:nama==anak" jwilder/whoami
```
and the webapp container will run on the **Server 3(172.16.1.201)**

### 1. ehazlett/interlock:1.3.0 

**ehazlett/interlock:1.3.0** cannot listen the docker events

### 2. ehazlett/interlock:master

**ehazlett/interlock:master** can listen the docker events, reload the nginx container, add the nginx record, but error nginx binding port, it's says that 
```
WARN[0001] Failed getting network for ep 2af9a1bd76e4c829a9a28da1fb3dd216f9cf8f6e8a6be800e488a007bd9f4db1 during sandbox b5f0b67b898a5ebd832ba7310185fd970025c9b588e387f6b0727ebdf33abb76 delete: network 6395d05318df30d7738fa7d45ea621e916c5
880d8ec131ece0bfbb64eb1bd94f not found
WARN[0001] Failed deleting endpoint a80d3842dca9652ff658a9a284a4ace11a7b9998d8926fb5ef8370ee296824d7: failed to get endpoint from store during Delete: could not find endpoint a80d3842dca9652ff658a9a284a4ace11a7b9998d8926fb5ef8370ee296824d
7: []
```
and when i check with docker ps, the nginx container is not binding any ports. But when i use docker inspect, the json output give the correct binding

### 3. ehazlett/interlock:1.2.0

**ehazlett/interlock:1.2.0** works fine, didn't get any errors :smile:

**Comment by ehazlett** [comment]
I have updated the docker client library and some other minor fixes.  Can you try the latest `ehazlett/interlock:dev` to see if this fixes?

**Comment by Kangmo** [comment]
Hi ehazlett, I tried the dev version and I hit this issue. 
But thanks for the great software. 

elk_interlock.1.husqf5e2n4ba@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:26Z" level=info msg="interlock 1.4.0-dev (c610d87)" 
elk_interlock.1.husqf5e2n4ba@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:26Z" level=error msg="Missing nginx configuration template: file=/etc/interlock/nginx.conf.template" ext=lb 
elk_interlock.1.husqf5e2n4ba@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:26Z" level=error msg="Use the TemplatePath option in your Interlock config.toml to set a custom location for the nginx configuration template" ext=lb 
elk_interlock.1.husqf5e2n4ba@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:26Z" level=error msg="Examples of an configuration template: url=https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx" ext=lb 
elk_interlock.1.husqf5e2n4ba@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:26Z" level=fatal msg="stat /etc/interlock/nginx.conf.template: no such file or directory" ext=lb 
elk_interlock.1.6skyz55xzuhb@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:32Z" level=info msg="interlock 1.4.0-dev (c610d87)" 
elk_interlock.1.6skyz55xzuhb@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:32Z" level=error msg="Missing nginx configuration template: file=/etc/interlock/nginx.conf.template" ext=lb 
elk_interlock.1.6skyz55xzuhb@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:32Z" level=error msg="Use the TemplatePath option in your Interlock config.toml to set a custom location for the nginx configuration template" ext=lb 
elk_interlock.1.6skyz55xzuhb@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:32Z" level=error msg="Examples of an configuration template: url=https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx" ext=lb 
elk_interlock.1.6skyz55xzuhb@ip-172-32-7-244-master-deeplog    | time="2017-04-30T09:53:32Z" level=fatal msg="stat /etc/interlock/nginx.conf.template: no such file or directory" ext=lb
