### ISSUE TITLE
Interlock dies if swarm node disappears

### ISSUE THREAD

**Issue by mbentley** [ehazlett/interlock#22]
I believe we had discussed this previously but I figured it would be worth tracking that interlock will die if a swarm node goes away, likely due to the error that occurs in swarm:
```
time="2015-02-16T02:12:43Z" level=error msg="Flagging node as dead. Updated state failed: 500 Internal Server Error: engine is shutdown\n" id="ZJKA:BBJB:KVQU:T2ID:KPMV:4V64:PYDN:UN4S:TH3Q:4PC6:W5HG:ONQK" name=docker2
2015/02/16 02:12:58 Event decoding failed: unexpected EOF
```

I'd expect that the problem is occurring during the `unexpected EOF` error so I'd be led to believe that this is actually an issue with swarm and how it is handing nodes going away.

Interlock handles the swarm manager going away just fine but this it chokes on.  I've ran into this when I have been attempting to upgrade the docker engine on by backend hosts and when the engine is restarted, interlock dies.

**Comment by ehazlett** [comment]
I'm not sure what interlock is choking on but I'll take a look.  Thanks!

**Comment by mbentley** [comment]
Nice work on the refactor!  Very slick!  In the new version, it looks like it is detecting when swarm is unavailable but it wasn't able to re-establish a connection to :
```
# docker logs -f interlock
time="2015-03-23T14:18:57Z" level="info" msg="using tls for communication with swarm"
time="2015-03-23T14:18:57Z" level="info" msg="interlock running version=0.2.0"
time="2015-03-23T14:18:57Z" level="info" msg="loaded plugin name=haproxy version=0.1"
time="2015-03-23T14:18:57Z" level="info" msg="[stats] sending stats every 10 seconds"
time="2015-03-23T14:18:57Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1"
time="2015-03-23T14:18:57Z" level="info" msg="[haproxy] ci.mbentley.dckrindy.io: upstream=192.168.1.61:49160"
time="2015-03-23T14:18:58Z" level="info" msg="[haproxy] proxy reloaded and ready"
time="2015-03-23T14:20:17Z" level="warning" msg="error receiving events; attempting to reconnect"
time="2015-03-23T14:20:18Z" level="error" msg="Get https://labrouter.core.dckrindy.io:3376/v1.15/events: read tcp 192.168.1.60:3376: connection reset by peer"
```

In this case, it was stuck until I restarted interlock.

Another time I tried `docker stop swarm; sleep 4; docker start swarm; docker logs -f interlock` and I am seeing an EOF error and interlock never connects back to swarm:
```
time="2015-03-23T14:23:30Z" level="info" msg="[stats] sending stats every 10 seconds"
time="2015-03-23T14:23:30Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1"
time="2015-03-23T14:23:30Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1"
time="2015-03-23T14:23:30Z" level="info" msg="[stats] sending stats every 10 seconds"
time="2015-03-23T14:23:47Z" level="error" msg="unexpected EOF"
```

I tried it once more and it did detect the drop and was able to reconnect so it is working sometimes :)

**Comment by ehazlett** [comment]
Thanks!  Ok - I'll take a look -- thanks for reporting :)

**Comment by ehazlett** [comment]
This is fixed in `ng`.  Please open a new issue if you continue to have issues.  Thanks!
