### ISSUE TITLE
interlock-extension for shipyard does not work

### ISSUE THREAD

**Issue by useltmann** [ehazlett/interlock#23]
hi,

this image does not work when installed as extension via shipyard. 
the output of `docker logs <id>` shows

    flag provided but not defined: -shipyard-url

and according to your swarm merge 11 days ago appearently you removed the shipyard config in `config.go`. there are even more files that get rid of shipyard code

**Comment by ehazlett** [comment]
Correct.  You will need to use the `v1` tag (`ehazlett/interlock:v1`) to use as an extension.  Shipyard is moving its backend to swarm so there will be less customization needed for integration.  I will update the docs.  Thanks!
