### ISSUE TITLE
Backend tries connecting to 0.0.0.0:<port>

### ISSUE THREAD

**Issue by wolfgang42** [ehazlett/interlock#24]
I'm trying Interlock on a brand-new CoreOS installation.
```bash
docker run -p 80:8080 ehazlett/interlock -swarm tcp://10.1.42.1:2375
docker run -ti -P -d --hostname www.example.com -e INTERLOCK_DATA='{"alias_domains": ["foo.com"], "port": 8080, "warm": true}' ehazlett/go-demo
```
Now I visit `/haproxy?stats`, and it reports the backends for `www_example_com_0` and `foo_com_0` as DOWN. `cat /proxy.conf` in the interlock container reveals the following line:
```
server foo_com_0 0.0.0.0:49155 check inter 5000
```

For some reason, Interlock is picking up 0.0.0.0 instead of the correct IP address, and I don't know enough about how Docker works to figure out why.

**Comment by ehazlett** [comment]
If you do not use interlock with swarm, you must specify the "proxy-backend-override-address" option as interlock will not be able to parse the IP from the event.  Only with swarm does the remote api have the node ip address.

**Comment by brunogoossens** [comment]
I tested this with a Swarm setup of 1 machine (swarm-agent and swarm-agent-manager on same machine). In this case the redirect rule is also set to 0.0.0.0. Maybe you can use the SWARM master Host IP if the node IP returns 0.0.0.0 ?
