### ISSUE TITLE
Security Vulnerability with Interlock Container

### ISSUE THREAD

**Issue by sjoshi10** [ehazlett/interlock#246]
@ehazlett Could you rebuild interlock with latest base image because we are seeing security vulnerabilities for packages inside interlock container. Fixes are already released by the vendor.

**Comment by ehazlett** [comment]
Latest image (`1.4.3`) has been rebuilt and pushed using the latest base images. 
```
ehazlett/interlock                   1.4.3               sha256:4cc1d5cfe73aa5e864a0d082e04ed46d56f115e569f8f7b6073ae07ef18cfc40   9238b1670d86        38 minutes ago      23.1MB
```

Thanks for the report!
