### ISSUE TITLE
Security Vulnerability with Interlock Container

### ISSUE THREAD

**Issue by sjoshi10** [ehazlett/interlock#247]
@ehazlett Could you rebuild interlock with latest base image again because we are seeing security vulnerabilities for packages inside interlock container. Fixes are already released by the vendor. Thanks!

**Comment by sjoshi10** [comment]
@ehazlett would you be able rebuild interlock image for us?

**Comment by ehazlett** [comment]
Latest has been built and pushed to `ehazlett/interlock:1.4.3` and `ehazlett/interlock:latest`

Thanks!
