### ISSUE TITLE
serviceEvent: service interlock is not an interlock service

### ISSUE THREAD

**Issue by andrijaperovic** [ehazlett/interlock#250]
Getting the following error which keeps repeating:

time="2019-06-21T07:34:49Z" level=debug msg="serviceEvent: service interlock is not an interlock service"
time="2019-06-21T07:34:49Z" level=debug msg="poll: checking service version" service_version=a01e1d
time="2019-06-21T07:34:49Z" level=debug msg="poll: tasks" numTasks=1 serviceVersion=a01e1d tasks="[{l4ojse6u55ulznixosnsp3b2m {{1615107} 2019-06-21 07:20:32.985303996 +0000 UTC 2019-06-21 07:20:41.07638041 +0000 UTC} { map[]} {0xc0002a3e40 <nil> <nil> 0xc0003d69c0 0xc00026ca80 0xc000235e50 [{i3ejq85oizree6szkgcqboyay [gateway_services] map[]}] <nil> 0 } ufle7c8lhmisxwto48vn5z6in 1 tbrcj83b4n2auiy0k6ljkbar1 {2019-06-21 07:20:40.998374954 +0000 UTC running started  0xc0003d52c0 {[]}} running [{{m7zoohlvpkigyyx0so0myedza {{6} 2019-06-17 22:53:52.87343001 +0000 UTC 2019-06-17 22:53:52.913970906 +0000 UTC} {{ingress map[]} 0xc0003d5300 false false false true 0xc00026cae0 <nil> swarm} {overlay map[com.docker.network.driver.overlay.vxlanid_list:4096]} 0xc00026cb40} [10.255.167.93/16]} {{i3ejq85oizree6szkgcqboyay {{1614722} 2019-06-21 06:38:50.313153415 +0000 UTC 2019-06-21 06:38:50.31446329 +0000 UTC} {{thunderbridge_thunderbridge-network map[com.docker.stack.namespace:thunderbridge]} 0xc0003d53c0 false false false false <nil> <nil> swarm} {overlay map[com.docker.network.driver.overlay.vxlanid_list:4116]} 0xc00026cbd0} [10.0.19.7/24]}] []}]" version=89d499

ID                  NAME                             MODE                REPLICAS            IMAGE                                                             PORTS
wo78i0fc9agy        adoring_rosalind                 replicated          1/1                 docker/ucp-interlock-extension:3.1.7
84am0d7aj51g        fervent_bassi                    replicated          1/1                 docker/ucp-interlock-proxy:3.1.7                                  *:8080->80/tcp, *:30000->443/tcp
a0hmxgt441de        interlock                        replicated          1/1                 docker/ucp-interlock:3.1.7

My compose file looks like the following: 
version: "3.2"
services:
  gateway_services:
    # replace username/repo:tag with your name and image details
    user: user_name
    image: image_name
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1600M
      restart_policy:
        condition: on-failure
      labels:
        com.docker.lb.hosts: public_hostname
        com.docker.lb.network: network
        com.docker.lb.port: 30001
        #com.docker.lb.ssl_passthrough: "true"
        com.docker.lb.ssl_cert: smf.uc.int.cert
        com.docker.lb.ssl_key: smf.uc.int.key
    ports:
      - "30001:8080"
    environment:
      METADATA: proxy-handles-tls
    networks:
      - thunderbridge-network
    secrets:
      - source: smf.uc.int.cert
        target: /run/secrets/cert.pem
      - source: smf.uc.int.key
        target: /run/secrets/key.pem
    volumes:
      - ./etc/config/properties:tomcat_volume
      - ./etc/config/keys:tomcat_volume

networks:
 network:
    driver: overlay
secrets:
  cert:
    file: ./cert
  key:
    file: ./key

config for interlock service creation: 

aperovic@smf-docker-eng-001:~$ cat config
ListenAddr = ":8080"
DockerURL = "unix:///var/run/docker.sock"
PollInterval = "3s"

[Extensions]
  [Extensions.default]
    Image = "docker/ucp-interlock-extension:3.1.7"
    Args = ["-D"]
    ProxyImage = "docker/ucp-interlock-proxy:3.1.7"
    ProxyArgs = []
    ProxyConfigPath = "/etc/nginx/nginx.conf"
    ProxyReplicas = 1
    ProxyStopGracePeriod = "3s"
    ServiceCluster = ""
    PublishMode = "ingress"
    PublishedPort = 8080
    TargetPort = 80
    PublishedSSLPort = 30000
    TargetSSLPort = 443
    [Extensions.default.Config]
      User = "nginx"
      PidPath = "/var/run/proxy.pid"
      WorkerProcesses = 1
      RlimitNoFile = 65535
      MaxConnections = 2048

docker service create statement: 

docker service create     --name interlock     --mount src=/var/run/docker.sock,dst=/var/run/docker.sock,type=bind     --network interlock     --constraint node.role==manager     --config src=service.interlock.conf,target=/config.toml     docker/ucp-interlock:3.1.7 -D run -c /config.toml

F5 routes to the master docker swarm host on port 30000 which I've configured as the PublishedSSLPort in my service.interlock.conf docker config.

**Comment by andrijaperovic** [comment]
Any ideas, @ehazlett ?

**Comment by ehazlett** [comment]
Hi.  This is a Docker EE image (version 2.x+ are EE only).  I suggest to open a support ticket with Docker as part of your subscription.  This error comes only when the labels are incorrect on the Interlock service.  Docker support can help troubleshoot through the error logs.  Thanks!

**Comment by andrijaperovic** [comment]
Will do, thank you for the suggestion. By interlock service I take it you mean the downstream service? Not the proxy service.

**Comment by ehazlett** [comment]
No the actual Interlock service appears to have been misconfigured.
