### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#26]
this was working fine. now when i try and run it i get the following:

panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x6f4ee0, 0x8ee83c)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*Manager).GenerateProxyConfig(0xc20800ebd0, 0xc208040500, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:209 +0x25a9
main.(*Manager).UpdateConfig(0xc20800ebd0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:272 +0xb3
main.(*Manager).Run(0xc20800ebd0, 0x0, 0x0)
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:379 +0xb3
main.main()
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/main.go:134 +0x92b

goroutine 19 [finalizer wait]:
runtime.park(0x419190, 0x8f2890, 0x8f0ae9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x8f2890, 0x8f0ae9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 29 [runnable]:
net/http.(*persistConn).readLoop(0xc2080442c0)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 22 [chan receive]:
main.(*Manager).reconnectOnFail(0xc20800ebd0)
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:348 +0x44
created by main.(*Manager).connect
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:325 +0x1e4

goroutine 24 [IO wait]:
net.runtime_pollWait(0x7fced77a8910, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208024680, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208024680, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208024620, 0xc208077000, 0x1000, 0x1000, 0x0, 0x7fced77a7418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208038078, 0xc208077000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/net.go:122 +0xe7
net/http.noteEOFReader.Read(0x7fced77a8a70, 0xc208038078, 0xc2080441b8, 0xc208077000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0xc2080406a0, 0xc208077000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:124 +0xca
bufio.(*Reader).fill(0xc2080046c0)
	/usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc2080046c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/bufio/bufio.go:298 +0x22c
net/http.readLine(0xc2080046c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/chunked.go:111 +0x59
net/http.(*chunkedReader).beginChunk(0xc20800f1d0)
	/usr/local/go/src/pkg/net/http/chunked.go:48 +0x45
net/http.(*chunkedReader).Read(0xc20800f1d0, 0xc208092000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/chunked.go:78 +0xc0
net/http.(*body).readLocked(0xc208042900, 0xc208092000, 0x200, 0x200, 0x54a272, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/transfer.go:577 +0x81
net/http.(*body).Read(0xc208042900, 0xc208092000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/transfer.go:572 +0x11a
net/http.(*bodyEOFSignal).Read(0xc208042940, 0xc208092000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/transport.go:1126 +0x254
encoding/json.(*Decoder).readValue(0xc208026340, 0x14, 0x0, 0x0)
	/usr/local/go/src/pkg/encoding/json/stream.go:124 +0x557
encoding/json.(*Decoder).Decode(0xc208026340, 0x63ca80, 0xc2080380a0, 0x0, 0x0)
	/usr/local/go/src/pkg/encoding/json/stream.go:44 +0x7a
github.com/samalba/dockerclient.(*DockerClient).getEvents(0xc208040540, 0xc208034a10, 0xc2080041e0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:259 +0x44d
created by github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents
	/var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:243 +0x83

goroutine 27 [select]:
net/http.(*persistConn).readLoop(0xc208044160)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc208044160)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 30 [select]:
net/http.(*persistConn).writeLoop(0xc2080442c0)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957

**Comment by emeasee** [comment]
Same issue for me:

```
panic: runtime error: slice bounds out of range

goroutine 24 [running]:
runtime.panic(0x6f4ee0, 0x8ee84f)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*EventHandler).Handle(0xc20803a048, 0xc208044040, 0xc2080041e0, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/handler.go:23 +0x38f
main.*EventHandler.Handle·fm(0xc208044040, 0xc2080041e0, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:331 +0x58
github.com/samalba/dockerclient.(*DockerClient).getEvents(0xc208086ce0, 0xc208037140, 0xc2080041e0, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:264 +0x5b9
created by github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:243 +0x83

goroutine 16 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.(*Manager).Run(0xc20808b1a0, 0x0, 0x0)
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:403 +0x2b9
main.main()
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/main.go:134 +0x92b

goroutine 19 [finalizer wait, 12 minutes]:
runtime.park(0x419190, 0x8f2890, 0x8f0ae9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x8f2890, 0x8f0ae9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 12 minutes]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 22 [chan receive, 12 minutes]:
main.(*Manager).reconnectOnFail(0xc20808b1a0)
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:348 +0x44
created by main.(*Manager).connect
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:325 +0x1e4

goroutine 32 [select, 9 minutes]:
net/http.(*persistConn).writeLoop(0xc208046a50)
        /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 34 [chan receive, 9 minutes]:
main.func·001()
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:391 +0x44
created by main.(*Manager).Run
        /var/lib/jenkins/workspace/interlock/src/github.com/ehazlett/interlock/controller/manager.go:400 +0x2aa

goroutine 31 [runnable]:
net/http.(*persistConn).readLoop(0xc208046a50)
        /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 29 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fc30880e050, 0x72, 0x0)
        /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208098680, 0x72, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208098680, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208098620, 0xc208041000, 0x400, 0x400, 0x0, 0x7fc30880c418, 0xb)
        /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20803a098, 0xc208041000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/pkg/net/net.go:122 +0xe7
crypto/tls.(*block).readFromUntil(0xc20808a150, 0x7fc30880e128, 0xc20803a098, 0x5, 0x0, 0x0)
        /usr/local/go/src/pkg/crypto/tls/conn.go:451 +0xd9
crypto/tls.(*Conn).readRecord(0xc2080722c0, 0x17, 0x0, 0x0)
        /usr/local/go/src/pkg/crypto/tls/conn.go:536 +0x1ff
crypto/tls.(*Conn).Read(0xc2080722c0, 0xc208061000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/pkg/crypto/tls/conn.go:901 +0x16a
net/http.noteEOFReader.Read(0x7fc30880ee88, 0xc2080722c0, 0xc208046318, 0xc208061000, 0x1000, 0x1000, 0x904c20, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0xc208042b00, 0xc208061000, 0x1000, 0x1000, 0xc20800ef80, 0x0, 0x0)
        <autogenerated>:124 +0xca
bufio.(*Reader).fill(0xc2080ba600)
        /usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0xc2080ba600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
net/http.(*persistConn).readLoop(0xc2080462c0)
        /usr/local/go/src/pkg/net/http/transport.go:782 +0x95
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 30 [select, 9 minutes]:
net/http.(*persistConn).writeLoop(0xc2080462c0)
        /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
```

**Comment by ehazlett** [comment]
This is fixed in the "plugins" branch which will be merged this week.
Thanks!

**Comment by emeasee** [comment]
Awesome, thanks for the good work

**Comment by ehazlett** [comment]
Thanks!

**Comment by ehazlett** [comment]
Plugins branch has been merged.  This should now be fixed.  Thanks!
