### ISSUE TITLE
not picking up changes

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#35]
sometimes the haproxy does not pick up changes that happen.
i will add new node to a pool or remove some and it will not show up.
i have to restart the container to see the changes. 

i dont see anything in the logs, so im not sure what to give you to help.

**Comment by ehazlett** [comment]
This can happen if the Swarm event stream goes away and then comes back.  Interlock re-connects but can sometimes not get the stream.  I'm not sure how we can debug -- if you can find a way to reproduce then I will do some digging.

**Comment by chromerobv** [comment]
so as a work around for now whenever i add new containers to a pool i restart the interlock container with just a docker restart. was working perfectly fine but randomly today the container died after restart with the following:

time="2015-06-08T18:33:01Z" level="debug" msg="[haproxy] jobs: 0"
time="2015-06-08T18:33:01Z" level="debug" msg="[haproxy] reload triggered"
time="2015-06-08T18:33:01Z" level="info" msg="[haproxy] proxy reloaded and ready"
panic: runtime error: slice bounds out of range

goroutine 25 [running]:
runtime.panic(0x7dd6a0, 0xc2944f)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*EventHandler).Handle(0xc20802a048, 0xc20803c600, 0xc208004360, 0x0, 0x0, 0x0)
	/go/src/github.com/ehazlett/interlock/interlock/handler.go:25 +0x296
main.*EventHandler.Handle·fm(0xc20803c600, 0xc208004360, 0x0, 0x0, 0x0)
	/go/src/github.com/ehazlett/interlock/interlock/manager.go:55 +0x58
github.com/samalba/dockerclient.(*DockerClient).getEvents(0xc208030840, 0xc208001300, 0xc208004360, 0x0, 0x0, 0x0)
	/go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:262 +0x3e0
created by github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents
	/go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:243 +0x83

goroutine 16 [chan receive, 4294 minutes]:
main.waitForInterrupt()
	/go/src/github.com/ehazlett/interlock/interlock/commands.go:23 +0x155
main.cmdStart(0xc208054180)
	/go/src/github.com/ehazlett/interlock/interlock/commands.go:88 +0xb0d
github.com/codegangsta/cli.Command.Run(0x830970, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0xc208029040, 0xc20800e000, 0x7, 0x7, 0x0, 0x0)
	/go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
	/go/src/github.com/ehazlett/interlock/interlock/main.go:98 +0x622

goroutine 19 [finalizer wait, 14 minutes]:
runtime.park(0x417980, 0xc40510, 0xc2b6e9)
	/usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc40510, 0xc2b6e9)
	/usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 4294 minutes]:
os/signal.loop()
	/usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 22 [chan receive, 4294 minutes]:
main.(*Manager).reconnectOnFail(0xc208010de0)
	/go/src/github.com/ehazlett/interlock/interlock/manager.go:72 +0x44
created by main.(*Manager).connect
	/go/src/github.com/ehazlett/interlock/interlock/manager.go:49 +0x1e2

goroutine 23 [chan receive, 4294 minutes]:
main.func·002()
	/go/src/github.com/ehazlett/interlock/interlock/manager.go:101 +0x4f
created by main.(*Manager).Run
	/go/src/github.com/ehazlett/interlock/interlock/manager.go:104 +0x92

goroutine 32 [select, 4294 minutes]:
net/http.(*persistConn).writeLoop(0xc208050160)
	/usr/src/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/src/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 33 [IO wait, 14 minutes]:
net.runtime_pollWait(0x7f21687b7b60, 0x72, 0x0)
	/usr/src/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20800e140, 0x72, 0x0, 0x0)
	/usr/src/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20800e140, 0x0, 0x0)
	/usr/src/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20800e0e0, 0xc20808c000, 0x1000, 0x1000, 0x0, 0x7f21687b62b8, 0xb)
	/usr/src/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20802a090, 0xc20808c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/pkg/net/net.go:122 +0xe7
net/http.noteEOFReader.Read(0x7f21687b7e68, 0xc20802a090, 0xc2080503c8, 0xc20808c000, 0x1000, 0x1000, 0xc58e60, 0x0, 0x0)
	/usr/src/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0xc208030820, 0xc20808c000, 0x1000, 0x1000, 0xc208034200, 0x0, 0x0)
	<autogenerated>:124 +0xca
bufio.(*Reader).fill(0xc2080049c0)
	/usr/src/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0xc2080049c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/pkg/bufio/bufio.go:132 +0x101
net/http.(*persistConn).readLoop(0xc208050370)
	/usr/src/go/src/pkg/net/http/transport.go:782 +0x95
created by net/http.(*Transport).dialConn
	/usr/src/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 29 [select, 4291 minutes]:
net.func·019()
	/usr/src/go/src/pkg/net/dnsclient_unix.go:184 +0x2ab
created by net.loadConfig
	/usr/src/go/src/pkg/net/dnsclient_unix.go:212 +0x153

goroutine 31 [runnable]:
net/http.(*persistConn).readLoop(0xc208050160)
	/usr/src/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/src/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 34 [select, 14 minutes]:
net/http.(*persistConn).writeLoop(0xc208050370)
	/usr/src/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/src/go/src/pkg/net/http/transport.go:601 +0x957
[root@horseshoe rvicchiullo]# docker start ff83cd85880d

**Comment by ehazlett** [comment]
There is reconnect functionality in the new `ng` version set to be released in a week or so.  This is fixed.  Thanks!
