### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by chromerobv** [ehazlett/interlock#36]
is there anyway to have the members of the pool named after the container names.
right now if the pool is named foo.mydomain.com the members show as foo_mydomain_dom_0, _1, etc...

it would be so much more helpful if it showed the actual name of the containers instead.

**Comment by chromerobv** [comment]
https://github.com/ehazlett/interlock/pull/38

**Comment by ehazlett** [comment]
+1

**Comment by ehazlett** [comment]
Fixed in #38
