### ISSUE TITLE
How to handle service upgrades?

### ISSUE THREAD

**Issue by pkaeding** [ehazlett/interlock#37]
I'm curious if Interlock does anything to support atomically swapping out versions of an application.  For instance, suppose you have 1 container running version `A` of your application.  If you start another container running version `A`, it should be added to the same backend pool, so HAProxy can balance between them.  

However, if you then deploy a container running version `B`, you likely don't want it added to the same backend pool as the version `A`s. Doing so would cause problems with the wrong versions of assets being requested (if a request for `/s/B/main.js` was received by a backend running version `A`, it would return 404, or worse, return version `A`, which may then be cached by the CDN), and behavior flapping back and forth from one request to another.

I think the thing to do would be to atomically remove the `A` backend pool, and replace it with a `B` backend pool, when a version `B` container is seen.

Does Interlock address this?  I took a quick look through the code, and didn't see anything, but it is quite possible I missed it.  If you think it is the right approach, I can try to take a stab at a PR implementing my idea.

**Comment by mbentley** [comment]
You are correct, it currently doesn't have any logic to handle that.

**Comment by ehazlett** [comment]
We would need to account some type of variable (perhaps a flag on the image ID).  Typically this has been pushed off to the deployment system.  We could add a flag in the `INTERLOCK_DATA` that would support this.  Perhaps something that makes sure only containers of the same image ID are added to the pool?

**Comment by chromerobv** [comment]
yeah. we handle this with a quick ansible playbook. on run we set a --label. then when we start up new container with the same label it first grabs all the old containers with the same label. then brings up the new ones, checks if they are working correctly then kills the old ones. if it doesnt come up correct then it kills the newly created ones.

**Comment by pkaeding** [comment]
@chromerobv That sounds a lot like the ansible deploy script I have for some non-dockerized services, but it works well because it doesn't update the HAProxy configs until it is sure the new services are up, and then it swaps the configs atomically. The problem here is that Interlock would add the new services to HAProxy before it is sure they are up (and more importantly, before it removes the old containers).  (Unless I'm misunderstanding what you are describing?)

**Comment by chromerobv** [comment]
true but i have it add it with a custom check and if that check isn't working then it isn't active in the pool yet.

**Comment by ehazlett** [comment]
There isn't any functionality to handle this.  Perhaps an extension in the future.  Closing for now.
