### ISSUE TITLE
error

### ISSUE THREAD

**Issue by normalfaults** [ehazlett/interlock#43]
getting this error while running interlock haproxy
time="2015-06-11T03:09:14Z" level="info" msg="using tls for communication with swarm" 
time="2015-06-11T03:09:17Z" level="info" msg="interlock running version=0.2.6 (043cb24)" 
time="2015-06-11T03:09:17Z" level="debug" msg="connecting to swarm on tcp://10.6.33.65:3376" 
time="2015-06-11T03:09:17Z" level="info" msg="loading plugin name=haproxy version=0.1" 
time="2015-06-11T03:09:17Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1" 
time="2015-06-11T03:09:17Z" level="debug" msg="[haproxy] update request received" 
time="2015-06-11T03:09:17Z" level="debug" msg="[haproxy] generating proxy config" 
time="2015-06-11T03:09:18Z" level="info" msg="[haproxy] aaron.java-test.dev: upstream=10.6.33.65:32768 container=java-getting-started" 
time="2015-06-11T03:09:18Z" level="debug" msg="[haproxy] adding alias java-test.dev for 47dc7d4cdb20" 
time="2015-06-11T03:09:18Z" level="debug" msg="[haproxy] adding host name=aaron_java-test_dev domain=aaron.java-test.dev" 
time="2015-06-11T03:09:18Z" level="debug" msg="[haproxy] adding host name=java-test_dev domain=java-test.dev" 
time="2015-06-11T03:09:18Z" level="debug" msg="[haproxy] jobs: 0" 
time="2015-06-11T03:09:18Z" level="debug" msg="[haproxy] reload triggered" 
time="2015-06-11T03:09:18Z" level="error" msg="[haproxy] error reloading: exit status 1"

docker run --name interlock --restart="always" -p 80:8080 -p 443:8443 -d -v /certs:/certs/:ro -e HAPROXY_SSL_CERT=/certs/server.pem ehazlett/interlock --swarm-url tcp://<ip>:3376 --swarm-tls-ca-cert=/certs/ca.pem --swarm-tls-cert=/certs/server.pem --swarm-tls-key=/certs/server.key --debug --plugin haproxy start

any ideas?
@ehazlett

**Comment by ehazlett** [comment]
Are you sure your SSL cert is formatted properly?  You can check the error
by "docker exec" to the container and manually running haproxy -- I want to
add that output to the container logs eventually.

**Comment by normalfaults** [comment]
I think you are right about the SSL Cert. I need to cat the cert and key together. +1 for adding the haproxy logs to the container logs would definitely make debugging easier. I will try with the new cert.

**Comment by normalfaults** [comment]
you were correct is was the ssl cert format. Thanks for the quick response!

**Comment by ehazlett** [comment]
yw -- glad you got it working :D
