### ISSUE TITLE
Interlock stops processing further events on swarm container error

### ISSUE THREAD

**Issue by mbentley** [ehazlett/interlock#45]
When running a interlock + nginx plugin against a swarm cluster, I am running into what looks like a race condition where interlock tries to query for a container that doesn't exist and swarm throws an error stating that the said container doesn't exist.  It seems that interlock stops processing further events.  Here is a gif of the error in action.  Interlock is on top, swarm on the bottom:

![interlock-swarm](http://i.imgur.com/b0OUmcQ.gif)

I am running swarm from master on all of my swarm nodes as well as master and interlock:latest (0.2.6)

**Comment by mbentley** [comment]
In testing, I found that if I switched my swarm-agent-master back to using `swarm:0.3.0-rc2`, I get the container errors but interlock continues to process events.

**Comment by ehazlett** [comment]
This should be fixed in the new `ng` branch.  Please re-open if you continue to notice issues.  Thanks!
