### ISSUE TITLE
nginx plugin - no default server when SSL enabled

### ISSUE THREAD

**Issue by mbentley** [ehazlett/interlock#52]
When enabling an endpoint that utilizes SSL, there is no default server for SSL connections.  This causes random backends to be exposed unintentionally.

**Comment by mbentley** [comment]
I am working on identifying what a proper fix would be.  My first thought would be something that can handle modifying https://github.com/ehazlett/interlock/blob/master/plugins/nginx/template.go#L53 to change the default server to serve both http and https.  The problem is that multiple lines would need to be added; similar to:

```
listen {{ .Port }};
listen {{ .SSLPort }};
ssl on;
ssl_certificate {{ .SSLCert }};
ssl_certificate_key {{ .SSLCertKey }};
```

I don't know if this breaks how the template would work but there would have to be some changes, especially since there would have to be some way to handle a default SSL certificate as well... ick!  It just seems to get tricky quickly.

**Comment by ehazlett** [comment]
I think this is why there was no default on SSL as is.  Let me think on this a bit :)

**Comment by wr0ngway** [comment]
+1 ran into a problem with multiple ssl vhosts leaking into each other
nginx doesn't check `server_name` unless it has to disambiguate `listen`, so by not having a default ssl listen, it ends up picking the first vhost ssl listen even when I'm requesting a different vhost that is no longer in the config.  A good read on it here: https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms

**Comment by wr0ngway** [comment]
Maybe something like: http://serverfault.com/questions/382606/nginx-serving-content-from-the-wrong-virtual-host-while-accessing-with-https

That is, use the snakeoil cert - to generate on ubuntu, install `ssl-cert` package, then if installing didn't create the snakeoil cert you can do so with `make-ssl-cert generate-default-snakeoil --force-overwrite`

**Comment by ehazlett** [comment]
This should be fixed with the new `ng` branch set to be released in a week or so.  Please re-open if you continue to notice the issue.  Thanks!

**Comment by SergiuCip** [comment]
Has the ng branch have been merged into the master branch, as I am unable to find it anywhere?

**Comment by mbentley** [comment]
@SergiuCip yes it has.  https://github.com/ehazlett/interlock/commit/3a36c7d0ded3a1ea21552977738f7c1aa07bcc45

**Comment by SergiuCip** [comment]
@mbentley Thanks for clarifying that. You wouldn't happen to know how to bring up multiple SSL NGINX Vhosts with their own SSL certs, as I have tried using the INTERLOCK_DATA as such:

INTERLOCK_DATA='{"alias_domains": ["foo.com"], "port": 443, "ssl_only": true, "warm": true}'     ehazlett/go-demo

but still keeps port 8080 instead of replacing it with 443, and I was wondering how do you pass the certs for a specific site? Something like this INTERLOC_DATA {SSLCertPath = ""} ?

Thanks a lot.

Sergiu

**Comment by mbentley** [comment]
It would be something like (ignore some of the values being different):
`{"hostname": "hostname", "domain": "example.com", "ssl": true, "ssl_only": true, "ssl_certificate": "server.pem", "ssl_certificate_key": "server.key"}`

So specifically `"ssl_certificate": "server.pem", "ssl_certificate_key": "server.key"`
