### ISSUE TITLE
docker machine, compose, swarm haproxy (or nginx) working example

### ISSUE THREAD

**Issue by lukemadera** [ehazlett/interlock#59]
I'm having trouble getting the reverse proxy to work with Docker Swarm.

I followed this tutorial https://blog.docker.com/2015/02/orchestrating-docker-with-machine-swarm-and-compose/

So I'm using docker-machine, docker-swarm, and scaling with docker-compose.

And I have my docker swarm running with 3 swarm nodes / agents.
I can access my public http site on all 3 individual IP addresses for the swarm agents but cannot figure out how to reverse proxy them to be accessible through ONE public, specified IP address.

My docker compose file looks like:
```
web:
  build: .
  ports:
    - "3000"
  links:
    - droppriceCode
droppriceCode:
  image: lukemadera/dropprice-code
```

`docker ps` outputs this:
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
04de9f99bda9        droppricecompose_web   "/bin/sh -c 'node run"   About an hour ago   Up 25 minutes       3002/tcp, 27017/tcp, 104.236.87.160:32781->3000/tcp   swarm-master/04de9f99bd_04de9f99bd_04de9f99bd_04de9f99bd_04de9f99bd_04de9f99bd_droppricecompose_web_3
3ed097d392be        droppricecompose_web   "/bin/sh -c 'node run"   5 hours ago         Up 25 minutes       3002/tcp, 104.236.204.109:3000->3000/tcp              swarm-02/droppricecompose_web_2
3c8f88b7832b        droppricecompose_web   "/bin/sh -c 'node run"   5 hours ago         Up 25 minutes       3002/tcp, 104.236.204.109:80->3000/tcp                swarm-02/droppricecompose_web_1
8d74da04e2c3        mongo                  "/entrypoint.sh mongo"   31 hours ago        Up 31 hours         27017/tcp                                             swarm-master/droppricecompose_mongo_1
```

So I tried this docker haproxy plugin:
I run `docker run -p 3000:80 -d -v /etc/docker:/etc/docker ehazlett/interlock --swarm-url $DOCKER_HOST --plugin haproxy start`

It ran the first time but I couldn't access any public webserver. I tried again but now it always gives an `unable to find a node with port 3000 available`

All my servers are on digitalocean:

- main server I'm running all the above commands from: `104.236.133.134`
- swarm master is `104.236.87.160`
- and then 3 separate swarm nodes with their own ip addresses.

I think I'm getting lost in all the ip addresses and ports. I'm not sure which ones to use where..

Again everything seems to be working except the final step of linking / proxying all the individual swarm node ip addresses into one public ip address. I can access each node individually just fine.
Any help would be greatly appreciated.
Thanks!

**Comment by ehazlett** [comment]
Sorry for the delay.  This needs to connect to a Swarm manager (not the nodes).  Interlock then receives the node IP and sets that in the upstream.
