### ISSUE TITLE
large number of containers cause denial of service

### ISSUE THREAD

**Issue by ehazlett** [ehazlett/interlock#6]
When starting or stopping a large number of instances, HAProxy will be continuously HUPd to be updated causing service interruption.

**Comment by ManMohanVyas** [comment]
hmm ..the solution can be to gather all the start stop request in/between some particular time span and then make the configuration at once and then do a single reload in that particular time span. any how a queue would be needed for sure.

**Comment by ehazlett** [comment]
This has been fixed in 6ecde26e6f
