### ISSUE TITLE
No connection to Swarm

### ISSUE THREAD

**Issue by helix01** [ehazlett/interlock#60]
Hi there,
im using shipyard v3 and want to use interlock/haproxy. I managed to get it running, but only direct via docker:
docker run -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock -e "HAPROXY_PROXY_BACKEND_OVERRIDE_ADDRESS=MY_PUBLIC_IP" -d ehazlett/interlock --plugin haproxy start

When im using the "stock" shipyard setup, how can i connect to swam?
docker run -p 80:80 -d ehazlett/interlock --swarm-url ?URL? --plugin haproxy start
I tried several combinations like localhost:2375 or 127.0.0.1:2375. With http and tcp. But the log says things like "connection refused". 

Thanks in advance

**Comment by ehazlett** [comment]
This needs to be connected to an accessible swarm endpoint.  By default there is no way to tell what that is so it resolves to localhost.  Simply set this to an accessible IP.
