### ISSUE TITLE
Bad certificats error when used on local Swarm created with Machine

### ISSUE THREAD

**Issue by lucj** [ehazlett/interlock#62]
Hi Evan,

When deploying this compose file on a VirtualBox Swarm created with Machine, I got some error from interlock regarding bad certificate.

Creation of the Swarm on VirtualBox

    # KV Store
    docker-machine create -d virtualbox consul
    eval "$(docker-machine env consul)"
    docker run -d -p "8500:8500" -h "consul" progrium/consul -server -bootstrap
    
    # Swarm master
    docker-machine create \
    -d virtualbox \
    --swarm --swarm-image="swarm" --swarm-master \
    --swarm-discovery="consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    demo0
    
    # Swarm node
    docker-machine create -d virtualbox \
    --swarm --swarm-image="swarm:1.0.0-rc2" \
    --swarm-discovery="consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    demo1

docker-compose.yml

    interlock:
      image: ehazlett/interlock
      ports:
        - "80:80"
      volumes:
        - /home/docker/.docker:/etc/docker  # Certs created by Machine are in /home/docker/.docker folder, right ?
      command: "--swarm-url tcp://192.168.99.101:2376 --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/cert.pem --swarm-tls-key=/etc/docker/key.pem --plugin haproxy start"
    db:
      image: mongo:3.0
      command: "--storageEngine wiredTiger"
      environment:
        - "constraint:node==demo0"
    api:
      image: lucj/message-app:v3
      environment:
        - MONGO_URL=mongodb://testscale_db_1:27017/messageApp
        - INTERLOCK_DATA={"hostname":"api","domain":"message-app.com"}

Compose ran with:

    docker-compose --x-networking --x-network-driver=overlay up

Connection Errors:

    interlock_1 | time="2015-11-19T11:20:14Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1"
    interlock_1 | time="2015-11-19T11:20:14Z" level="warning" msg="Get https://192.168.99.101:2376/v1.15/containers/json?all=0&size=0: remote error: bad certificate"
    interlock_1 | time="2015-11-19T11:20:14Z" level="error" msg="[haproxy] error reloading: exit status 1"
    interlock_1 | time="2015-11-19T11:20:14Z" level="warning" msg="error receiving events; attempting to reconnect"
    interlock_1 | time="2015-11-19T11:20:14Z" level="error" msg="Get https://192.168.99.101:2376/v1.15/events: remote error: bad certificate"

Any idea what I'm missing ?

**Comment by normalfaults** [comment]
There might be a certs subdirectory in .docker ?

**Comment by lucj** [comment]
When I created with Machine, the Docker host contains certs in /home/docker/.docker

    docker@demo0:~/.docker$ pwd
    /home/docker/.docker
    docker@demo0:~/.docker$ ls
    ca.pem    cert.pem  key.pem

**Comment by lucj** [comment]
Seems like this is linked to a problem with the certificates when creating the Docker host with machine and this is not linked to Interlock.
https://github.com/docker/machine/issues/2405
