### ISSUE TITLE
Nginx not setting proxy headers

### ISSUE THREAD

**Issue by wr0ngway** [ehazlett/interlock#65]
Since interlock is using nginx strictly as a proxy, it should set the headers to pass through the data most proxies do:

    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

Theses can be set in either the http, server or location contexts:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

**Comment by wr0ngway** [comment]
Actually, now that I look at the code, its only missing X-Forwarded-Proto and HOST

**Comment by ehazlett** [comment]
closing as #66 was merged. thanks!!

**Comment by md5** [comment]
Unconditionally setting `X-Forwarded-Proto` to `$scheme` means that you'll lose any incoming `X-Forwarded-Proto` that is received by `nginx`. This can be problematic if you have a load balancer (for example an AWS Elastic Load Balancer) that is terminating SSL and forwarding on requests with plain HTTP. For the `jwilder/nginx-proxy` image, I submitted a PR in October 2014 to use `map` to only set `X-Forwarded-Proto` to `$scheme` if it was not already set.

cf. https://github.com/jwilder/nginx-proxy/pull/41

**Comment by ehazlett** [comment]
good point. I'm going to revert that. can we get these integrated @wr0ngway ?

**Comment by md5** [comment]
Here's the relevant lines of the `jwilder/nginx-proxy` config: https://github.com/jwilder/nginx-proxy/blob/1e0b9301747a48d7a51d5d088ac5df16bde878c0/nginx.tmpl#L18-L23

**Comment by wr0ngway** [comment]
Good point, I'll make the change, thanks.
Should HOST also be treated the same way?

**Comment by wr0ngway** [comment]
Addressed in #68

**Comment by md5** [comment]
@wr0ngway I don't think it can hurt to set `Host`. [The docs](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) say that passing `Host` through is the default, but they also say this:

> These directives are inherited from the previous level if and only if there are no proxy_set_header directives defined on the current level. By default, only two fields are redefined:
>
>> proxy_set_header Host       $proxy_host;
>> proxy_set_header Connection close;

It's unclear to me whether this means that setting `proxy_set_header` at a level will also mean that the defaults aren't used.

**Comment by md5** [comment]
Now that I see the defaults, it probably also makes sense to set `Connection: close`. However, this is another area where we had to add special handling in `jwilder/nginx-proxy`. Specifically, we set `Connection: close` in all cases, *except* when the `Upgrade` header is present. This was done to accommodate proxying Websockets. See here: https://github.com/jwilder/nginx-proxy/blob/1e0b9301747a48d7a51d5d088ac5df16bde878c0/nginx.tmpl#L25-L30

**Comment by md5** [comment]
See https://github.com/jwilder/nginx-proxy/pull/46 for the PR and linked discussions.

**Comment by wr0ngway** [comment]
Ok, looks like interlock/nginx already has that upgrade/close logic for WS in the nginx template ( https://github.com/ehazlett/interlock/blob/master/plugins/nginx/template.go#L46-L49 ), so this should be ready to go now @ehazlett

**Comment by wr0ngway** [comment]
That is, ready to go in PR #68 - since you did a revert, I figured a new branch/commit would ensure a clean merge

**Comment by ehazlett** [comment]
closing as #68 was merged :)  thanks!
