### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by wr0ngway** [ehazlett/interlock#69]
Not really an issue, but does anyone have any directions on how to build/compile this repo.  It could just be my lack of familiarity with go, but a wiki page would be appreciated.  Uncertain as to what my GOPATH should be set to, and how to fetch dependencies, etc.  Running ```make``` or ```make add-deps``` with a GOPATH of the repo's dir fails to find packages:
```
mconway@wrongway ~/workspace/interlock(master)$ echo $GOPATH
/Users/mconway/workspace/interlock
mconway@wrongway ~/workspace/interlock(master)$ make add-deps
godep: cannot find package "_/Users/mconway/workspace/interlock" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/_/Users/mconway/workspace/interlock (from $GOROOT)
	/Users/mconway/workspace/interlock/src/_/Users/mconway/workspace/interlock (from $GOPATH)
godep: cannot find package "github.com/samalba/dockerclient" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/samalba/dockerclient (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/samalba/dockerclient (from $GOPATH)
godep: error loading dependencies
make: *** [add-deps] Error 1
mconway@wrongway ~/workspace/interlock(master)$ make
commands.go:15:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/Sirupsen/logrus (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/Sirupsen/logrus (from $GOPATH)
commands.go:16:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/codegangsta/cli (from $GOPATH)
commands.go:17:2: cannot find package "github.com/ehazlett/interlock" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock (from $GOPATH)
commands.go:18:2: cannot find package "github.com/ehazlett/interlock/plugins" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/plugins (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/plugins (from $GOPATH)
plugins.go:5:2: cannot find package "github.com/ehazlett/interlock/plugins/example" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/plugins/example (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/plugins/example (from $GOPATH)
plugins.go:6:2: cannot find package "github.com/ehazlett/interlock/plugins/haproxy" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/plugins/haproxy (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/plugins/haproxy (from $GOPATH)
plugins.go:7:2: cannot find package "github.com/ehazlett/interlock/plugins/nginx" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/plugins/nginx (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/plugins/nginx (from $GOPATH)
plugins.go:8:2: cannot find package "github.com/ehazlett/interlock/plugins/stats" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/plugins/stats (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/plugins/stats (from $GOPATH)
commands.go:19:2: cannot find package "github.com/ehazlett/interlock/version" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/ehazlett/interlock/version (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/ehazlett/interlock/version (from $GOPATH)
handler.go:8:2: cannot find package "github.com/samalba/dockerclient" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/samalba/dockerclient (from $GOROOT)
	/Users/mconway/workspace/interlock/src/github.com/samalba/dockerclient (from $GOPATH)
make: *** [build] Error 1

```

**Comment by wr0ngway** [comment]
Ok, after some iteration, this is what I have so far:
```
export GOPATH=~/workspace/go
export PATH=$PATH:$GOPATH/bin
mkdir -p $GOPATH
cd $GOPATH
go get github.com/tools/godep

mkdir -p $GOPATH/src/github.com/ehazlett
git clone git@github.com:ehazlett/interlock.git $GOPATH/src/github.com/ehazlett/interlock
go get -v github.com/ehazlett/interlock

cd $GOPATH/src/github.com/ehazlett/interlock
make add-deps
# make still fails - unable to find the following two dependencies, so get themmanually
go get github.com/codegangsta/cli 
go get github.com/Sirupsen/logrus

make
```

The final make runs for a while, so its doing something, but still fails with the following:

```
# github.com/ehazlett/interlock/plugins/stats
../plugins/stats/stats.go:173: cInfo.Node undefined (type *dockerclient.ContainerInfo has no field or method Node)
../plugins/stats/stats.go:174: cInfo.Node undefined (type *dockerclient.ContainerInfo has no field or method Node)
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 2
```

Any ideas?

**Comment by ehazlett** [comment]
Sorry about that :)  I just added some dev docs:
https://github.com/ehazlett/interlock#building

Hopefully that helps!

**Comment by wr0ngway** [comment]
Ok, I took a look, but I'm not getting very far - excuse me if I'm just being a go newb :)  Do I have to do something special to get/enable the vendor experiment aside from setting that environment variable?
This is what I did:

    > # installed from https://golang.org/dl/
    > go version
    go version go1.5.1 linux/amd64
    > cd /tmp
    > git clone https://github.com/ehazlett/interlock.git
    > cd interlock
    > export GOPATH=`pwd`
    > export GO15VENDOREXPERIMENT=1
    > make
    commands.go:15:2: cannot find package "github.com/Sirupsen/logrus" in any of:
      /usr/local/go/src/github.com/Sirupsen/logrus (from $GOROOT)
      /tmp/interlock/src/github.com/Sirupsen/logrus (from $GOPATH)
    commands.go:16:2: cannot find package "github.com/codegangsta/cli" in any of:
      /usr/local/go/src/github.com/codegangsta/cli (from $GOROOT)
      /tmp/interlock/src/github.com/codegangsta/cli (from $GOPATH)
    commands.go:17:2: cannot find package "github.com/ehazlett/interlock" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock (from $GOPATH)
    commands.go:18:2: cannot find package "github.com/ehazlett/interlock/manager" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/manager (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/manager (from $GOPATH)
    commands.go:19:2: cannot find package "github.com/ehazlett/interlock/plugins" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/plugins (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/plugins (from $GOPATH)
    plugins.go:5:2: cannot find package "github.com/ehazlett/interlock/plugins/example" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/plugins/example (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/plugins/example (from $GOPATH)
    plugins.go:6:2: cannot find package "github.com/ehazlett/interlock/plugins/haproxy" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/plugins/haproxy (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/plugins/haproxy (from $GOPATH)
    plugins.go:7:2: cannot find package "github.com/ehazlett/interlock/plugins/nginx" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/plugins/nginx (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/plugins/nginx (from $GOPATH)
    plugins.go:8:2: cannot find package "github.com/ehazlett/interlock/plugins/stats" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/plugins/stats (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/plugins/stats (from $GOPATH)
    commands.go:20:2: cannot find package "github.com/ehazlett/interlock/version" in any of:
      /usr/local/go/src/github.com/ehazlett/interlock/version (from $GOROOT)
      /tmp/interlock/src/github.com/ehazlett/interlock/version (from $GOPATH)
    make: *** [build] Error 1
    > go get github.com/tools/godep
    > export PATH=$PATH:$GOPATH/bin
    > godep version
    godep v30 (linux/amd64/go1.5.1)
    > make add-deps
    godep: cannot find package "_/tmp/interlock" in any of:
      /usr/local/go/src/_/tmp/interlock (from $GOROOT)
      /tmp/interlock/src/_/tmp/interlock (from $GOPATH)
    godep: cannot find package "github.com/samalba/dockerclient" in any of:
      /usr/local/go/src/github.com/samalba/dockerclient (from $GOROOT)
      /tmp/interlock/src/github.com/samalba/dockerclient (from $GOPATH)
    godep: error loading dependencies
    make: *** [add-deps] Error 1

**Comment by ehazlett** [comment]
Yes it's a Go path issue.  The easiest way to fix this is to actually clone
the source to your GOPATH.  For example, I use ~/dev/gocode as my GOPATH.
Then I clone my repos there.  For example, I clone interlock to
~/dev/gocode/src/github.com/ehazlett/interlock.  This way Go can find it.

**Comment by ehazlett** [comment]
I will also add a docker container build target to build everything in a
container.  I usually do this in my projects to prevent these path issues :)

**Comment by wr0ngway** [comment]
Ok, great, that worked, thanks!  A docker build sounds like a great idea too

**Comment by ehazlett** [comment]
Ok added a build-container target and updated readme.  Thanks!

**Comment by wr0ngway** [comment]
Ok, I was able to build an image, but required a few tweaks.  Not doing a PR, as I'm not sure if these are valid for all:
* Dockerfile.build: golang:1.5-cross doesn't exist, only 1.4-cross does, but it worked for me without cross (I only need linux)
* Dockerfile: Had to add --force-yes to the haproxy/nginx install lines
* Makefile: Had to manually remove dependency on build in the other phony targets since build-container was producing the artefact.  Been a while since I've done much Makefiles, but there probably is a way to get build to not trigger if interlock/interlock exists

**Comment by md5** [comment]
@wr0ngway What you did with respect to `1.5-cross` was correct. See https://github.com/docker-library/golang/issues/63

**Comment by chromerobv** [comment]
hate to res an old topic but i am having trouble with build.

# make build
# github.com/ehazlett/interlock/ext/lb
../../ext/lb/lb.go:375: l.client.CopyToContainer undefined (type *dockerclient.DockerClient has no field or method CopyToContainer)
make: *** [build-static] Error 2
