### ISSUE TITLE
Support version X.Y instead of just X.Y.Z

### ISSUE THREAD

**Issue by gittycat** [ehazlett/interlock#77]
It would help to be able to retrieve the latest 1.0.x version by using
```
docker run ehazlett/interlock:1.0
```
This currently doesn't work as the full `ehzalett/interlock:1.0.0` is needed.

**Comment by ehazlett** [comment]
A tag has been created `ehazlett/interlock:1.0` -> `ehazlett/interlock:1.0.0`.  Thanks!
