### ISSUE TITLE
haproxy bug: ordering of ssl / verify none / sni causes proxy.conf to fail parsing

### ISSUE THREAD

**Issue by owen** [ehazlett/interlock#81]
Hey there!

It looks like the ordering of ssl / verify / SNI in the haproxy `server` stanza causes the proxy.conf to not be parsed.

Tested: interlock 0.3.3 -- but I think this bug will also be present in interlock 1.0.0 because the ordering is the same.

Configuration:

`docker run -e INTERLOCK_DATA='{"ssl_backend_tls_verify": "none", "ssl_backend": true}' --hostname foo.bar.baz -p 3000 dtr.foo/test/test-repo:latest`

`docker run -p 80:80 -p 443:443 -v /etc/docker:/etc/docker:ro -v /root:/ssl:ro -e HAPROXY_SSL_CERT=/ssl/wildcard.certs ehazlett/interlock --swarm-url tcp://swarm-path:4000 --plugin haproxy --swarm-tls-ca-cert /etc/docker/ca.pem --swarm-tls-cert /etc/docker/cert.pem --swarm-tls-key /etc/docker/key.pem start`

Once `test/test-repo` has started up, the following messages are observed in the `ehazlett/interlock` logs:

    time="2016-03-03T20:32:08Z" level=error msg="error reloading haproxy: exit status 1"
    time="2016-03-03T20:32:08Z" level=error msg="[haproxy] error reloading: exit status 1"
    time="2016-03-03T20:32:08Z" level=warning msg="error receiving events; attempting to reconnect"

When I connect to the interlock container:

    # cat /proxy.conf
    (config elided)
    server stoic_shaw 3.101.113.47:32777 check inter 5000 ssl sni req.hdr(Host) verify none

    # haproxy -d -c -f proxy.conf
    [WARNING] 062/205826 (31) : config : log format ignored for frontend 'http-default' since it has no log address.
    [ALERT] 062/205826 (31) : Proxy 'XXX', server 'stoic_shaw' [proxy.conf:40] verify is enabled by default but no CA file specified. If you're running on a LAN where you're certain to trust the server's certificate, please set an explicit 'verify none' statement on the 'server' line, or use 'ssl-server-verify none' in the global section to disable server-side verifications by default.
    [WARNING] 062/205826 (31) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
    [ALERT] 062/205826 (31) : Fatal errors found in configuration.

The issue seems to be the server line: `server stoic_shaw 3.101.113.47:32777 check inter 5000 ssl sni req.hdr(Host) verify none`

If I change the ordering to put verify none *before* sni, as such: `server stoic_shaw 3.101.113.47:32777 check inter 5000 ssl verify none sni req.hdr(Host)`, interlock starts & runs as expected.

This is a head scratcher; reading the HAProxy docs seems to indicate the difference in ordering _should_ be irrelevant...

I'm going to send a message to the HAProxy mailing list & dig on the code there.

If you would like, I can send in a fix to Interlock to reorder the config files.  interlock:0.3.3 & interlock:master best?

thanks for some cool software!

**Comment by ehazlett** [comment]
Hmm yes this does seem odd.  I would definitely welcome a contribution :)  I will also see if I can find anything related.

Thanks!

**Comment by owen** [comment]
http://article.gmane.org/gmane.comp.web.haproxy/26894

Definitely looks like an HAProxy specific issue.

A PR is incoming for 1.0.0 - I haven't tested it, but it's pretty darn basic.
I'd like to send one for 0.3.3; not sure if you're interested in rebuilding.  This was tested & works fine.

I can't do a PR against a basic commit though.  Github :-1:  Are you interested in running a back ports branch or anything?  if so, I can PR that one out as well.

**Comment by ehazlett** [comment]
This was fixed in 1.1.0.  Closing.
