### ISSUE TITLE
Externalize the extension configuration templates

### ISSUE THREAD

**Issue by everett-toews** [ehazlett/interlock#91]
## Feature Request

Currently the extension configuration templates like [nginx/template.go](https://github.com/ehazlett/interlock/blob/master/ext/nginx/template.go) and [haproxy/template.go](https://github.com/ehazlett/interlock/blob/master/ext/haproxy/template.go) are compiled right into Interlock. That means you're locked into the how that configuration is done.

The extension configuration templates should be externalized as simple text files that can make use of Interlock variables (e.g. `{{ $host.Name }}`). You could then include the configuration templates in your `Dockerfile` to be consumed by Interlock.

**Comment by everett-toews** [comment]
@ehazlett If you think this is a good feature for Interlock, I'd be willing to start work on it. Seems like it would be best to base it on the [overlay-support](https://github.com/ehazlett/interlock/tree/overlay-support) branch.

What do you think?

**Comment by ehazlett** [comment]
Ya +1.  I think it would be valuable.  Yes, please use the `overlay-support` branch as that contains a decent refactor (more tests, etc) and will be merged soon.  Thanks!
