### ISSUE TITLE
Doesn't appear to restart container outside swarm

### ISSUE THREAD

**Issue by blackxored** [ehazlett/interlock#95]
If you run it outside swarm, both interlock and the external nginx proxy, it fails to reload/restart the container. Unless I missed a config option, I'm trying to run my LB outside of my swarm cluster until /maybe even after overlay arrives.

**Comment by ehazlett** [comment]
This is by design.  Interlock must run as part of the Swarm cluster as it needs the event stream to detect when containers go up/down.
