### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by SergiuCip** [ehazlett/interlock#99]
I was wondering if you could implement multiple SSL websites and also if support SFTP?

Thanks,

Regards,
Sergiu

**Comment by adamjimenez** [comment]
I achieved SSH/ SFTP by mapping a random port to each container.

**Comment by ehazlett** [comment]
You can use multiple SSL -- it depends on your backend.  See the "SSL" options here https://github.com/ehazlett/interlock/blob/master/docs/configuration.md.

There has been request for TCP support -- that would probably help your SFTP.  No plans as far as when.
